In [1]:
import pandas as pd
import numpy as np

### Train set

In [2]:
df_kyc = pd.read_excel("C:/Users/mwamb/Desktop/Desktop/Pezesha/train_set/kyc data.xlsx")
df_loansdata = pd.read_csv("C:/Users/mwamb/Desktop/Desktop/Pezesha/train_set/loans_data.csv")
df_transactiondata= pd.read_csv("C:/Users/mwamb/Desktop/Desktop/Pezesha/train_set/transaction_data.csv")
#,names=header_list_loan,header=None

In [3]:
df_kyc.head()

,customer_id,DOB,customer_date_created,channel,sub_channel,depot_name,route_name,ekyc_status
0,918bf22c-4507-4e26-8d88-464705cf6fd3,NaN,2020-12-31,Open Air,Car Vendor,Kisumu,Nyalenda,False
1,458a39da-5bd1-494b-931c-529fe9f69ae7,NaN,2021-09-28,Duka,Chemist/ Pharmacy,Kaloleni,Mathare 2,False
2,207e9b13-a5d2-4d3c-8226-10cf94d865af,1983-01-12,2019-03-19,Duka,Duka Retailer,Thika Town,Matuu,True
3,4efe9aa4-20b8-463a-a24e-731aa0bd123c,NaN,2020-10-15,Duka,Duka Retailer,Eldoret,Mwanzo,False
4,6752e4ba-a48b-45c8-85ec-3a04a3dcc8b7,NaN,2020-10-19,Duka,Duka Retailer,Eldoret,Iten,False

In [4]:
df_loansdata.head()

,id,merchant_score_reason_id,merchant_id,partner,loan_id,loan_data,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,created_at,updated_at
0,29416,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,NaN,100800,"{""loan_id"": 100800","""app_amount"": ""9160.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:22:01""","""duration"": 7",...,"""avg_mobi_loan_principal_amount"": 5389.89","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-27 13:36:45+00,54:44.3
1,29415,107657.0,652b7ea4-c015-4d44-9c05-b97eefa4482a,NaN,100799,"{""loan_id"": 100799","""app_amount"": ""4979.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:21:20""","""duration"": 7",...,"""avg_mobi_loan_principal_amount"": 8521.82","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 35000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-27 13:36:44+00,55:49.7
2,29413,107631.0,7e03d9e4-ce43-4db0-adf4-9cb10e91077e,NaN,100797,"{""loan_id"": 100797","""app_amount"": ""26608.00""","""app_interest_rate"": ""0.50""","""mpesa_time"": ""2021-09-27 10:11:05""","""duration"": 7",...,"""avg_mobi_loan_principal_amount"": 3000","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 3000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-27 13:26:17+00,46:10.6
3,29411,107293.0,42aa7d55-f12f-4769-89ff-bfb1f68f8313,NaN,100795,"{""loan_id"": 100795","""app_amount"": ""59799.00""","""app_interest_rate"": ""0.50""","""mpesa_time"": ""2021-09-27 09:59:58""","""duration"": 7",...,"""avg_mobi_loan_principal_amount"": 4060","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 7500","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-27 13:06:28+00,35:41.2
4,29408,107365.0,916e0d3a-97b0-4f4e-a67a-3bb8f560b344,NaN,100792,"{""loan_id"": 100792","""app_amount"": ""12849.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 09:46:30""","""duration"": 7",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-09-27 12:56:46+00,54:55.7

In [5]:
df_loansdata.columns = ["id","merchant_score_reason_id","merchant_id","partner","loan_id","loan_data",
                         "app_amount", "app_interest_rate", "mpesa_time","duration", "merchant_id1", "loan_status", 
                         "created_at", "customer_id", "loan_count",
                        "crb_data", "npa_closed_accounts",
                            "pa_open_accounts_with_dh", "pa_closed_mobi_loan_accounts_with_dh", 
                                      "npa_open_accounts","pa_closed_accounts", "pa_accounts_with_dh",
                                      "npa_open_mobi_loan_accounts","last_mobi_loan_listing_date_my_sector",
                                      "pa_accounts", "pa_closed_mobi_loan_accounts",
                                      "last_mobi_loan_principal_amount", "mobi_loan_accounts",
                                      "credit_history", "min_mobi_loan_principal_amount",
                                      "avg_mobi_loan_principal_amount",
                                      "last_mobi_loan_listing_date_other_sectors",
                                      "max_mobi_loan_principal_amount", 
                                      "npa_closed_mobi_loan_accounts", "pa_open_accounts",
                                      "npa_accounts", "pa_open_mobi_loan_accounts_with_dh", 
                                      "pa_closed_accounts_with_dh","created_at","updated_at"
]

In [6]:
df_loansdata['loan_status']

0          "loan_status": "Paid"
1          "loan_status": "Paid"
2          "loan_status": "Paid"
3          "loan_status": "Paid"
4          "loan_status": "Paid"
                  ...
4332     "loan_status": "Funded"
4333     "loan_status": "Funded"
4334       "loan_status": "Paid"
4335     "loan_status": "Funded"
4336     "loan_status": "Funded"
Name: loan_status, Length: 4337, dtype: object

In [7]:
df_transactiondata.head()

,id,master_record_id,merchant_id,score_data,master_created_at,created_at
0,113009,185593,900e701b-f239-4c6b-9381-11d47cca2746,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...",NaN,2021-09-30 19:07:00+00
1,113008,185592,900e701b-f239-4c6b-9381-11d47cca2746,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...",NaN,2021-09-30 19:06:00+00
2,113007,185591,2df350b0-1f8d-4375-a49c-25ab4ee00088,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...",NaN,2021-09-30 19:01:00+00
3,113006,185589,2df350b0-1f8d-4375-a49c-25ab4ee00088,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...",NaN,2021-09-30 19:00:00+00
4,113005,185588,2df350b0-1f8d-4375-a49c-25ab4ee00088,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...",NaN,2021-09-30 18:59:01+00

In [8]:

df_transactiondata_split = df_transactiondata['score_data'].str.split(", ", expand=True)
data = df_transactiondata_split.values.tolist()
names = ["customer_id", "transaction_days","num_orders","most_recent_transaction","earliest_transaction"
        ,"active_days","total_sales","unique_days_sales","sales_activity_ratio","expected_orders(fundable_merchants)",
        "avg_order_size","depot_name","hypothetical_weekly_order","txn_weeks","avg_del/week","funding_label",
        "average_daily_sales","reason_type","min_loan","max_loan","graduation_difference","recency",
        "frequency","monetary_value","r_quartile","m_quartile","f_quartile","RMFScore","merchant_score"]
new_df_transactiondata = pd.DataFrame(data, columns=names)

In [9]:
new_df_transactiondata.head()

,customer_id,transaction_days,num_orders,most_recent_transaction,earliest_transaction,active_days,total_sales,unique_days_sales,sales_activity_ratio,expected_orders(fundable_merchants),...,max_loan,graduation_difference,recency,frequency,monetary_value,r_quartile,m_quartile,f_quartile,RMFScore,merchant_score
0,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...","""transaction_days"": 89","""num_orders"": 64","""most_recent_transaction"": ""2021-09-29""","""earliest_transaction"": ""2021-07-02""","""active_days"": 90","""total_sales"": 1014484","""unique_days_sales"": 52","""sales_activity_ratio"": 0.58","""expected_orders(fundable_merchants)"": 26.0",...,"""max_loan"": 71013","""graduation_difference"": 31561","""recency"": 90","""frequency"": 0.58","""monetary_value"": 1014484","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
1,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...","""transaction_days"": 89","""num_orders"": 64","""most_recent_transaction"": ""2021-09-29""","""earliest_transaction"": ""2021-07-02""","""active_days"": 90","""total_sales"": 1014484","""unique_days_sales"": 52","""sales_activity_ratio"": 0.58","""expected_orders(fundable_merchants)"": 26.0",...,"""max_loan"": 71013","""graduation_difference"": 31561","""recency"": 90","""frequency"": 0.58","""monetary_value"": 1014484","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
2,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""","""earliest_transaction"": ""2021-07-02""","""active_days"": 91","""total_sales"": 335188","""unique_days_sales"": 58","""sales_activity_ratio"": 0.64","""expected_orders(fundable_merchants)"": 26.0",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
3,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""","""earliest_transaction"": ""2021-07-02""","""active_days"": 91","""total_sales"": 335188","""unique_days_sales"": 58","""sales_activity_ratio"": 0.64","""expected_orders(fundable_merchants)"": 26.0",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
4,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""","""earliest_transaction"": ""2021-07-02""","""active_days"": 91","""total_sales"": 335188","""unique_days_sales"": 58","""sales_activity_ratio"": 0.64","""expected_orders(fundable_merchants)"": 26.0",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"

In [10]:
final_df_transactiondata = pd.concat([df_transactiondata, new_df_transactiondata], axis=1, join='inner')

In [11]:
final_df_transactiondata.head()

,id,master_record_id,merchant_id,score_data,master_created_at,created_at,customer_id,transaction_days,num_orders,most_recent_transaction,...,max_loan,graduation_difference,recency,frequency,monetary_value,r_quartile,m_quartile,f_quartile,RMFScore,merchant_score
0,113009,185593,900e701b-f239-4c6b-9381-11d47cca2746,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...",NaN,2021-09-30 19:07:00+00,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...","""transaction_days"": 89","""num_orders"": 64","""most_recent_transaction"": ""2021-09-29""",...,"""max_loan"": 71013","""graduation_difference"": 31561","""recency"": 90","""frequency"": 0.58","""monetary_value"": 1014484","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
1,113008,185592,900e701b-f239-4c6b-9381-11d47cca2746,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...",NaN,2021-09-30 19:06:00+00,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...","""transaction_days"": 89","""num_orders"": 64","""most_recent_transaction"": ""2021-09-29""",...,"""max_loan"": 71013","""graduation_difference"": 31561","""recency"": 90","""frequency"": 0.58","""monetary_value"": 1014484","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
2,113007,185591,2df350b0-1f8d-4375-a49c-25ab4ee00088,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...",NaN,2021-09-30 19:01:00+00,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
3,113006,185589,2df350b0-1f8d-4375-a49c-25ab4ee00088,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...",NaN,2021-09-30 19:00:00+00,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
4,113005,185588,2df350b0-1f8d-4375-a49c-25ab4ee00088,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...",NaN,2021-09-30 18:59:01+00,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"

In [12]:
# Remove column name 'A'
final_df_transactiondata.drop(['score_data'], axis = 1, inplace = True)

In [13]:
final_df_transactiondata.head()

,id,master_record_id,merchant_id,master_created_at,created_at,customer_id,transaction_days,num_orders,most_recent_transaction,earliest_transaction,...,max_loan,graduation_difference,recency,frequency,monetary_value,r_quartile,m_quartile,f_quartile,RMFScore,merchant_score
0,113009,185593,900e701b-f239-4c6b-9381-11d47cca2746,NaN,2021-09-30 19:07:00+00,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...","""transaction_days"": 89","""num_orders"": 64","""most_recent_transaction"": ""2021-09-29""","""earliest_transaction"": ""2021-07-02""",...,"""max_loan"": 71013","""graduation_difference"": 31561","""recency"": 90","""frequency"": 0.58","""monetary_value"": 1014484","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
1,113008,185592,900e701b-f239-4c6b-9381-11d47cca2746,NaN,2021-09-30 19:06:00+00,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...","""transaction_days"": 89","""num_orders"": 64","""most_recent_transaction"": ""2021-09-29""","""earliest_transaction"": ""2021-07-02""",...,"""max_loan"": 71013","""graduation_difference"": 31561","""recency"": 90","""frequency"": 0.58","""monetary_value"": 1014484","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
2,113007,185591,2df350b0-1f8d-4375-a49c-25ab4ee00088,NaN,2021-09-30 19:01:00+00,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""","""earliest_transaction"": ""2021-07-02""",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
3,113006,185589,2df350b0-1f8d-4375-a49c-25ab4ee00088,NaN,2021-09-30 19:00:00+00,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""","""earliest_transaction"": ""2021-07-02""",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
4,113005,185588,2df350b0-1f8d-4375-a49c-25ab4ee00088,NaN,2021-09-30 18:59:01+00,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""","""earliest_transaction"": ""2021-07-02""",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"

In [14]:
final_df_transactiondata.loc[final_df_transactiondata['id']==107661.0]

,id,master_record_id,merchant_id,master_created_at,created_at,customer_id,transaction_days,num_orders,most_recent_transaction,earliest_transaction,...,max_loan,graduation_difference,recency,frequency,monetary_value,r_quartile,m_quartile,f_quartile,RMFScore,merchant_score
5340,107661,173626,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,NaN,2021-09-27 13:25:00+00,"{""customer_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""transaction_days"": 88","""num_orders"": 82","""most_recent_transaction"": ""2021-09-25""","""earliest_transaction"": ""2021-06-29""",...,"""max_loan"": 19422","""graduation_difference"": 8632","""recency"": 89","""frequency"": 0.81","""monetary_value"": 274396","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"

### Margin the Train data

In [15]:
# Remove column name 'A'
df_loansdata.drop(['id'], axis = 1, inplace = True)

In [16]:
df_loansdata.head()

,merchant_score_reason_id,merchant_id,partner,loan_id,loan_data,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,...,avg_mobi_loan_principal_amount,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,NaN,100800,"{""loan_id"": 100800","""app_amount"": ""9160.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:22:01""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...",...,"""avg_mobi_loan_principal_amount"": 5389.89","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-27 13:36:45+00,54:44.3
1,107657.0,652b7ea4-c015-4d44-9c05-b97eefa4482a,NaN,100799,"{""loan_id"": 100799","""app_amount"": ""4979.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:21:20""","""duration"": 7","""merchant_id"": ""652b7ea4-c015-4d44-9c05-b97ee...",...,"""avg_mobi_loan_principal_amount"": 8521.82","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 35000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-27 13:36:44+00,55:49.7
2,107631.0,7e03d9e4-ce43-4db0-adf4-9cb10e91077e,NaN,100797,"{""loan_id"": 100797","""app_amount"": ""26608.00""","""app_interest_rate"": ""0.50""","""mpesa_time"": ""2021-09-27 10:11:05""","""duration"": 7","""merchant_id"": ""7e03d9e4-ce43-4db0-adf4-9cb10...",...,"""avg_mobi_loan_principal_amount"": 3000","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 3000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-27 13:26:17+00,46:10.6
3,107293.0,42aa7d55-f12f-4769-89ff-bfb1f68f8313,NaN,100795,"{""loan_id"": 100795","""app_amount"": ""59799.00""","""app_interest_rate"": ""0.50""","""mpesa_time"": ""2021-09-27 09:59:58""","""duration"": 7","""merchant_id"": ""42aa7d55-f12f-4769-89ff-bfb1f...",...,"""avg_mobi_loan_principal_amount"": 4060","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 7500","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-27 13:06:28+00,35:41.2
4,107365.0,916e0d3a-97b0-4f4e-a67a-3bb8f560b344,NaN,100792,"{""loan_id"": 100792","""app_amount"": ""12849.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 09:46:30""","""duration"": 7","""merchant_id"": ""916e0d3a-97b0-4f4e-a67a-3bb8f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-09-27 12:56:46+00,54:55.7

In [17]:
df_loansdata.rename(columns = {'merchant_score_reason_id':'id'}, inplace = True)

In [18]:
df_loansdata.head(1)

,id,merchant_id,partner,loan_id,loan_data,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,...,avg_mobi_loan_principal_amount,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,NaN,100800,"{""loan_id"": 100800","""app_amount"": ""9160.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:22:01""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...",...,"""avg_mobi_loan_principal_amount"": 5389.89","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-27 13:36:45+00,54:44.3

In [19]:
final_df_transactiondata.head(1)

,id,master_record_id,merchant_id,master_created_at,created_at,customer_id,transaction_days,num_orders,most_recent_transaction,earliest_transaction,...,max_loan,graduation_difference,recency,frequency,monetary_value,r_quartile,m_quartile,f_quartile,RMFScore,merchant_score
0,113009,185593,900e701b-f239-4c6b-9381-11d47cca2746,NaN,2021-09-30 19:07:00+00,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...","""transaction_days"": 89","""num_orders"": 64","""most_recent_transaction"": ""2021-09-29""","""earliest_transaction"": ""2021-07-02""",...,"""max_loan"": 71013","""graduation_difference"": 31561","""recency"": 90","""frequency"": 0.58","""monetary_value"": 1014484","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"

In [20]:
# applying merge
train = df_loansdata.merge(final_df_transactiondata[['id']])

In [21]:
train.head(2)

,id,merchant_id,partner,loan_id,loan_data,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,...,avg_mobi_loan_principal_amount,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,NaN,100800,"{""loan_id"": 100800","""app_amount"": ""9160.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:22:01""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...",...,"""avg_mobi_loan_principal_amount"": 5389.89","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-27 13:36:45+00,54:44.3
1,107657.0,652b7ea4-c015-4d44-9c05-b97eefa4482a,NaN,100799,"{""loan_id"": 100799","""app_amount"": ""4979.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:21:20""","""duration"": 7","""merchant_id"": ""652b7ea4-c015-4d44-9c05-b97ee...",...,"""avg_mobi_loan_principal_amount"": 8521.82","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 35000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-27 13:36:44+00,55:49.7

In [22]:
for cols in train.columns:
    print(cols)

id
merchant_id
partner
loan_id
loan_data
app_amount
app_interest_rate
mpesa_time
duration
merchant_id1
loan_status
created_at
customer_id
loan_count
crb_data
npa_closed_accounts
pa_open_accounts_with_dh
pa_closed_mobi_loan_accounts_with_dh
npa_open_accounts
pa_closed_accounts
pa_accounts_with_dh
npa_open_mobi_loan_accounts
last_mobi_loan_listing_date_my_sector
pa_accounts
pa_closed_mobi_loan_accounts
last_mobi_loan_principal_amount
mobi_loan_accounts
credit_history
min_mobi_loan_principal_amount
avg_mobi_loan_principal_amount
last_mobi_loan_listing_date_other_sectors
max_mobi_loan_principal_amount
npa_closed_mobi_loan_accounts
pa_open_accounts
npa_accounts
pa_open_mobi_loan_accounts_with_dh
pa_closed_accounts_with_dh
created_at
updated_at

In [23]:
df_kyc.head()

,customer_id,DOB,customer_date_created,channel,sub_channel,depot_name,route_name,ekyc_status
0,918bf22c-4507-4e26-8d88-464705cf6fd3,NaN,2020-12-31,Open Air,Car Vendor,Kisumu,Nyalenda,False
1,458a39da-5bd1-494b-931c-529fe9f69ae7,NaN,2021-09-28,Duka,Chemist/ Pharmacy,Kaloleni,Mathare 2,False
2,207e9b13-a5d2-4d3c-8226-10cf94d865af,1983-01-12,2019-03-19,Duka,Duka Retailer,Thika Town,Matuu,True
3,4efe9aa4-20b8-463a-a24e-731aa0bd123c,NaN,2020-10-15,Duka,Duka Retailer,Eldoret,Mwanzo,False
4,6752e4ba-a48b-45c8-85ec-3a04a3dcc8b7,NaN,2020-10-19,Duka,Duka Retailer,Eldoret,Iten,False

In [24]:
df_kyc.rename(columns = {'customer_id':'merchant_id'}, inplace = True)

In [25]:
df_kyc.head(2)

,merchant_id,DOB,customer_date_created,channel,sub_channel,depot_name,route_name,ekyc_status
0,918bf22c-4507-4e26-8d88-464705cf6fd3,NaN,2020-12-31,Open Air,Car Vendor,Kisumu,Nyalenda,False
1,458a39da-5bd1-494b-931c-529fe9f69ae7,NaN,2021-09-28,Duka,Chemist/ Pharmacy,Kaloleni,Mathare 2,False

In [26]:
train.head()

,id,merchant_id,partner,loan_id,loan_data,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,...,avg_mobi_loan_principal_amount,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,NaN,100800,"{""loan_id"": 100800","""app_amount"": ""9160.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:22:01""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...",...,"""avg_mobi_loan_principal_amount"": 5389.89","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-27 13:36:45+00,54:44.3
1,107657.0,652b7ea4-c015-4d44-9c05-b97eefa4482a,NaN,100799,"{""loan_id"": 100799","""app_amount"": ""4979.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:21:20""","""duration"": 7","""merchant_id"": ""652b7ea4-c015-4d44-9c05-b97ee...",...,"""avg_mobi_loan_principal_amount"": 8521.82","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 35000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-27 13:36:44+00,55:49.7
2,107631.0,7e03d9e4-ce43-4db0-adf4-9cb10e91077e,NaN,100797,"{""loan_id"": 100797","""app_amount"": ""26608.00""","""app_interest_rate"": ""0.50""","""mpesa_time"": ""2021-09-27 10:11:05""","""duration"": 7","""merchant_id"": ""7e03d9e4-ce43-4db0-adf4-9cb10...",...,"""avg_mobi_loan_principal_amount"": 3000","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 3000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-27 13:26:17+00,46:10.6
3,107293.0,42aa7d55-f12f-4769-89ff-bfb1f68f8313,NaN,100795,"{""loan_id"": 100795","""app_amount"": ""59799.00""","""app_interest_rate"": ""0.50""","""mpesa_time"": ""2021-09-27 09:59:58""","""duration"": 7","""merchant_id"": ""42aa7d55-f12f-4769-89ff-bfb1f...",...,"""avg_mobi_loan_principal_amount"": 4060","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 7500","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-27 13:06:28+00,35:41.2
4,107365.0,916e0d3a-97b0-4f4e-a67a-3bb8f560b344,NaN,100792,"{""loan_id"": 100792","""app_amount"": ""12849.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 09:46:30""","""duration"": 7","""merchant_id"": ""916e0d3a-97b0-4f4e-a67a-3bb8f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-09-27 12:56:46+00,54:55.7

In [27]:
# applying merge
df_train = train.merge(df_kyc[['merchant_id']])

In [28]:
df_train.head()

,id,merchant_id,partner,loan_id,loan_data,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,...,avg_mobi_loan_principal_amount,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,NaN,100800,"{""loan_id"": 100800","""app_amount"": ""9160.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:22:01""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...",...,"""avg_mobi_loan_principal_amount"": 5389.89","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-27 13:36:45+00,54:44.3
1,98125.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,NaN,100339,"{""loan_id"": 100339","""app_amount"": ""8517.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-18 15:23:04""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...",...,"""avg_mobi_loan_principal_amount"": 5389.89","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-18 18:36:39+00,44:39.4
2,84249.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,NaN,99723,"{""loan_id"": 99723","""app_amount"": ""7635.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-07 11:45:41""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...",...,"""avg_mobi_loan_principal_amount"": 5389.89","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-07 14:57:22+00,56:36.6
3,74877.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,NaN,99359,"{""loan_id"": 99359","""app_amount"": ""7635.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-08-31 09:01:56""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...",...,"""avg_mobi_loan_principal_amount"": 5389.89","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-08-31 12:08:12+00,48:15.4
4,61454.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,NaN,98522,"{""loan_id"": 98522","""app_amount"": ""7635.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-08-16 08:52:59""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...",...,"""avg_mobi_loan_principal_amount"": 5389.89","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-08-23 12:41:30+00,50:01.1

In [29]:
df_train.columns

Index(['id', 'merchant_id', 'partner', 'loan_id', 'loan_data', 'app_amount',
       'app_interest_rate', 'mpesa_time', 'duration', 'merchant_id1',
       'loan_status', 'created_at', 'customer_id', 'loan_count', 'crb_data',
       'npa_closed_accounts', 'pa_open_accounts_with_dh',
       'pa_closed_mobi_loan_accounts_with_dh', 'npa_open_accounts',
       'pa_closed_accounts', 'pa_accounts_with_dh',
       'npa_open_mobi_loan_accounts', 'last_mobi_loan_listing_date_my_sector',
       'pa_accounts', 'pa_closed_mobi_loan_accounts',
       'last_mobi_loan_principal_amount', 'mobi_loan_accounts',
       'credit_history', 'min_mobi_loan_principal_amount',
       'avg_mobi_loan_principal_amount',
       'last_mobi_loan_listing_date_other_sectors',
       'max_mobi_loan_principal_amount', 'npa_closed_mobi_loan_accounts',
       'pa_open_accounts', 'npa_accounts',
       'pa_open_mobi_loan_accounts_with_dh', 'pa_closed_accounts_with_dh',
       'created_at', 'updated_at'],
      dtype='object')

### Test set

In [30]:
df_testkyc = pd.read_excel("C:/Users/mwamb/Desktop/Desktop/Pezesha/test set/kyc data.xlsx")
df_testloans=pd.read_excel("C:/Users/mwamb/Desktop/Desktop/Pezesha/test set/loans data.xlsx")
df_submission = pd.read_excel("C:/Users/mwamb/Desktop/Desktop/Pezesha/test set/submissionExample.xlsx")
df_testtransaction = pd.read_csv("C:/Users/mwamb/Desktop/Desktop/Pezesha/test set/transaction_data.csv")

In [31]:
df_testkyc.head()

,customer_id,DOB,customer_date_created,channel,sub_channel,depot_name,route_name,ekyc_status
0,918bf22c-4507-4e26-8d88-464705cf6fd3,NaN,2020-12-31,Open Air,Car Vendor,Kisumu,Nyalenda,False
1,458a39da-5bd1-494b-931c-529fe9f69ae7,NaN,2021-09-28,Duka,Chemist/ Pharmacy,Kaloleni,Mathare 2,False
2,207e9b13-a5d2-4d3c-8226-10cf94d865af,1983-01-12,2019-03-19,Duka,Duka Retailer,Thika Town,Matuu,True
3,4efe9aa4-20b8-463a-a24e-731aa0bd123c,NaN,2020-10-15,Duka,Duka Retailer,Eldoret,Mwanzo,False
4,6752e4ba-a48b-45c8-85ec-3a04a3dcc8b7,NaN,2020-10-19,Duka,Duka Retailer,Eldoret,Iten,False

In [32]:
df_testloans.head()

,id,merchant_score_reason_id,merchant_id,loan_id,loan_data,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,created_at,updated_at
0,29640,111915.0,40998a72-655b-48ab-be6d-5ba70c03fc6f,101051,"{""loan_id"": 101051","""app_amount"": ""1891.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 16:44:33""","""duration"": 7","""merchant_id"": ""40998a72-655b-48ab-be6d-5ba70...",...,"""avg_mobi_loan_principal_amount"": 8405.71","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 30000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 3","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-30 19:56:20+00,00:33:42.100000
1,29638,111603.0,3a4f60b6-be62-47a9-9c81-67f3caada902,101048,"{""loan_id"": 101048","""app_amount"": ""1520.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 15:56:51""","""duration"": 7","""merchant_id"": ""3a4f60b6-be62-47a9-9c81-67f3c...",...,"""avg_mobi_loan_principal_amount"": 613.33","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 4000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-30 19:06:30+00,00:16:14.300000
2,29637,111703.0,c198ed2e-5383-4a11-8b4d-e0f93466fbc9,101046,"{""loan_id"": 101046","""app_amount"": ""1568.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:26:10""","""duration"": 7","""merchant_id"": ""c198ed2e-5383-4a11-8b4d-e0f93...",...,"""avg_mobi_loan_principal_amount"": 0","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 0","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-30 17:36:15+00,00:36:29.600000
3,29636,112113.0,2c44c80b-19ff-4c25-9706-65bae6cbfda6,101045,"{""loan_id"": 101045","""app_amount"": ""7855.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:02:57""","""duration"": 7","""merchant_id"": ""2c44c80b-19ff-4c25-9706-65bae...",...,"""avg_mobi_loan_principal_amount"": 9507.14","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 12450","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 2","""npa_accounts"": 2","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-30 17:16:19+00,00:33:41.800000
4,29635,112338.0,9f68c51b-ceae-40d4-b1c2-c454bfb80e29,101044,"{""loan_id"": 101044","""app_amount"": ""3656.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 13:59:49""","""duration"": 7","""merchant_id"": ""9f68c51b-ceae-40d4-b1c2-c454b...",...,"""avg_mobi_loan_principal_amount"": 1500","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 1500","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-30 17:06:16+00,00:54:48.300000

In [33]:
df_testtransaction.head()

,id,master_record_id,merchant_id,score_data,master_created_at,created_at
0,113009,185593,900e701b-f239-4c6b-9381-11d47cca2746,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...",NaN,2021-09-30 19:07:00+00
1,113008,185592,900e701b-f239-4c6b-9381-11d47cca2746,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...",NaN,2021-09-30 19:06:00+00
2,113007,185591,2df350b0-1f8d-4375-a49c-25ab4ee00088,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...",NaN,2021-09-30 19:01:00+00
3,113006,185589,2df350b0-1f8d-4375-a49c-25ab4ee00088,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...",NaN,2021-09-30 19:00:00+00
4,113005,185588,2df350b0-1f8d-4375-a49c-25ab4ee00088,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...",NaN,2021-09-30 18:59:01+00

In [34]:
# df_transactiondata['score_data'].str.split(',', expand=True)

df_testtransaction_split = df_testtransaction['score_data'].str.split(", ", expand=True)
data = df_testtransaction_split.values.tolist()
names = ["customer_id", "transaction_days","num_orders","most_recent_transaction","earliest_transaction"
        ,"active_days","total_sales","unique_days_sales","sales_activity_ratio","expected_orders(fundable_merchants)",
        "avg_order_size","depot_name","hypothetical_weekly_order","txn_weeks","avg_del/week","funding_label",
        "average_daily_sales","reason_type","min_loan","max_loan","graduation_difference","recency",
        "frequency","monetary_value","r_quartile","m_quartile","f_quartile","RMFScore","merchant_score"]
new_df_testtransaction = pd.DataFrame(data, columns=names)

In [35]:
new_df_testtransaction.head()

,customer_id,transaction_days,num_orders,most_recent_transaction,earliest_transaction,active_days,total_sales,unique_days_sales,sales_activity_ratio,expected_orders(fundable_merchants),...,max_loan,graduation_difference,recency,frequency,monetary_value,r_quartile,m_quartile,f_quartile,RMFScore,merchant_score
0,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...","""transaction_days"": 89","""num_orders"": 64","""most_recent_transaction"": ""2021-09-29""","""earliest_transaction"": ""2021-07-02""","""active_days"": 90","""total_sales"": 1014484","""unique_days_sales"": 52","""sales_activity_ratio"": 0.58","""expected_orders(fundable_merchants)"": 26.0",...,"""max_loan"": 71013","""graduation_difference"": 31561","""recency"": 90","""frequency"": 0.58","""monetary_value"": 1014484","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
1,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...","""transaction_days"": 89","""num_orders"": 64","""most_recent_transaction"": ""2021-09-29""","""earliest_transaction"": ""2021-07-02""","""active_days"": 90","""total_sales"": 1014484","""unique_days_sales"": 52","""sales_activity_ratio"": 0.58","""expected_orders(fundable_merchants)"": 26.0",...,"""max_loan"": 71013","""graduation_difference"": 31561","""recency"": 90","""frequency"": 0.58","""monetary_value"": 1014484","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
2,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""","""earliest_transaction"": ""2021-07-02""","""active_days"": 91","""total_sales"": 335188","""unique_days_sales"": 58","""sales_activity_ratio"": 0.64","""expected_orders(fundable_merchants)"": 26.0",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
3,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""","""earliest_transaction"": ""2021-07-02""","""active_days"": 91","""total_sales"": 335188","""unique_days_sales"": 58","""sales_activity_ratio"": 0.64","""expected_orders(fundable_merchants)"": 26.0",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
4,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""","""earliest_transaction"": ""2021-07-02""","""active_days"": 91","""total_sales"": 335188","""unique_days_sales"": 58","""sales_activity_ratio"": 0.64","""expected_orders(fundable_merchants)"": 26.0",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"

In [36]:
final_df_testtransactions = pd.concat([df_testtransaction, new_df_testtransaction], axis=1, join='inner')

In [37]:
# Remove column name 'A'
final_df_testtransactions.drop(['score_data'], axis = 1, inplace = True)

In [38]:
final_df_testtransactions.head()

,id,master_record_id,merchant_id,master_created_at,created_at,customer_id,transaction_days,num_orders,most_recent_transaction,earliest_transaction,...,max_loan,graduation_difference,recency,frequency,monetary_value,r_quartile,m_quartile,f_quartile,RMFScore,merchant_score
0,113009,185593,900e701b-f239-4c6b-9381-11d47cca2746,NaN,2021-09-30 19:07:00+00,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...","""transaction_days"": 89","""num_orders"": 64","""most_recent_transaction"": ""2021-09-29""","""earliest_transaction"": ""2021-07-02""",...,"""max_loan"": 71013","""graduation_difference"": 31561","""recency"": 90","""frequency"": 0.58","""monetary_value"": 1014484","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
1,113008,185592,900e701b-f239-4c6b-9381-11d47cca2746,NaN,2021-09-30 19:06:00+00,"{""customer_id"": ""900e701b-f239-4c6b-9381-11d47...","""transaction_days"": 89","""num_orders"": 64","""most_recent_transaction"": ""2021-09-29""","""earliest_transaction"": ""2021-07-02""",...,"""max_loan"": 71013","""graduation_difference"": 31561","""recency"": 90","""frequency"": 0.58","""monetary_value"": 1014484","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
2,113007,185591,2df350b0-1f8d-4375-a49c-25ab4ee00088,NaN,2021-09-30 19:01:00+00,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""","""earliest_transaction"": ""2021-07-02""",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
3,113006,185589,2df350b0-1f8d-4375-a49c-25ab4ee00088,NaN,2021-09-30 19:00:00+00,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""","""earliest_transaction"": ""2021-07-02""",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"
4,113005,185588,2df350b0-1f8d-4375-a49c-25ab4ee00088,NaN,2021-09-30 18:59:01+00,"{""customer_id"": ""2df350b0-1f8d-4375-a49c-25ab4...","""transaction_days"": 90","""num_orders"": 84","""most_recent_transaction"": ""2021-09-30""","""earliest_transaction"": ""2021-07-02""",...,"""max_loan"": 23202","""graduation_difference"": 10312","""recency"": 91","""frequency"": 0.64","""monetary_value"": 335188","""r_quartile"": 4","""m_quartile"": 1","""f_quartile"": 1","""RMFScore"": 411","""merchant_score"": 235}"

In [39]:
df_testloans.columns = ["id","merchant_score_reason_id","merchant_id","loan_id","loan_data",
"app_amount", "app_interest_rate", "mpesa_time", "duration",
"merchant_id1", "created_at", "customer_id", "loan_count", "crb_data", "npa_closed_accounts",
"pa_open_accounts_with_dh", "pa_closed_mobi_loan_accounts_with_dh", "npa_open_accounts",
"pa_closed_accounts", "pa_accounts_with_dh", "npa_open_mobi_loan_accounts", "last_mobi_loan_listing_date_my_sector",
"pa_accounts", "pa_closed_mobi_loan_accounts", "last_mobi_loan_principal_amount", 
"mobi_loan_accounts", "credit_history", "min_mobi_loan_principal_amount", "avg_mobi_loan_principal_amount",
"last_mobi_loan_listing_date_other_sectors", "max_mobi_loan_principal_amount",
"npa_closed_mobi_loan_accounts", "pa_open_accounts", "npa_accounts", "pa_open_mobi_loan_accounts_with_dh",
"pa_closed_accounts_with_dh","created_at","updated_at"
]

In [40]:
df_testloans.head()

,id,merchant_score_reason_id,merchant_id,loan_id,loan_data,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,...,avg_mobi_loan_principal_amount,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,updated_at
0,29640,111915.0,40998a72-655b-48ab-be6d-5ba70c03fc6f,101051,"{""loan_id"": 101051","""app_amount"": ""1891.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 16:44:33""","""duration"": 7","""merchant_id"": ""40998a72-655b-48ab-be6d-5ba70...",...,"""avg_mobi_loan_principal_amount"": 8405.71","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 30000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 3","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-30 19:56:20+00,00:33:42.100000
1,29638,111603.0,3a4f60b6-be62-47a9-9c81-67f3caada902,101048,"{""loan_id"": 101048","""app_amount"": ""1520.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 15:56:51""","""duration"": 7","""merchant_id"": ""3a4f60b6-be62-47a9-9c81-67f3c...",...,"""avg_mobi_loan_principal_amount"": 613.33","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 4000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-30 19:06:30+00,00:16:14.300000
2,29637,111703.0,c198ed2e-5383-4a11-8b4d-e0f93466fbc9,101046,"{""loan_id"": 101046","""app_amount"": ""1568.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:26:10""","""duration"": 7","""merchant_id"": ""c198ed2e-5383-4a11-8b4d-e0f93...",...,"""avg_mobi_loan_principal_amount"": 0","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 0","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-30 17:36:15+00,00:36:29.600000
3,29636,112113.0,2c44c80b-19ff-4c25-9706-65bae6cbfda6,101045,"{""loan_id"": 101045","""app_amount"": ""7855.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:02:57""","""duration"": 7","""merchant_id"": ""2c44c80b-19ff-4c25-9706-65bae...",...,"""avg_mobi_loan_principal_amount"": 9507.14","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 12450","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 2","""npa_accounts"": 2","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-30 17:16:19+00,00:33:41.800000
4,29635,112338.0,9f68c51b-ceae-40d4-b1c2-c454bfb80e29,101044,"{""loan_id"": 101044","""app_amount"": ""3656.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 13:59:49""","""duration"": 7","""merchant_id"": ""9f68c51b-ceae-40d4-b1c2-c454b...",...,"""avg_mobi_loan_principal_amount"": 1500","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 1500","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-30 17:06:16+00,00:54:48.300000

In [41]:
# Remove column name 'A'
df_testloans.drop(['id'], axis = 1, inplace = True)

In [42]:
df_testloans.rename(columns = {'merchant_score_reason_id':'id'}, inplace = True)

In [43]:
# applying merge
test = df_testloans.merge(final_df_testtransactions[['id']])

In [44]:
test.head()

,id,merchant_id,loan_id,loan_data,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,...,avg_mobi_loan_principal_amount,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,updated_at
0,111915.0,40998a72-655b-48ab-be6d-5ba70c03fc6f,101051,"{""loan_id"": 101051","""app_amount"": ""1891.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 16:44:33""","""duration"": 7","""merchant_id"": ""40998a72-655b-48ab-be6d-5ba70...","""created_at"": ""2021-09-30 16:44:26""",...,"""avg_mobi_loan_principal_amount"": 8405.71","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 30000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 3","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-30 19:56:20+00,00:33:42.100000
1,111603.0,3a4f60b6-be62-47a9-9c81-67f3caada902,101048,"{""loan_id"": 101048","""app_amount"": ""1520.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 15:56:51""","""duration"": 7","""merchant_id"": ""3a4f60b6-be62-47a9-9c81-67f3c...","""created_at"": ""2021-09-30 15:56:45""",...,"""avg_mobi_loan_principal_amount"": 613.33","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 4000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-30 19:06:30+00,00:16:14.300000
2,111703.0,c198ed2e-5383-4a11-8b4d-e0f93466fbc9,101046,"{""loan_id"": 101046","""app_amount"": ""1568.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:26:10""","""duration"": 7","""merchant_id"": ""c198ed2e-5383-4a11-8b4d-e0f93...","""created_at"": ""2021-09-30 14:26:02""",...,"""avg_mobi_loan_principal_amount"": 0","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 0","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-30 17:36:15+00,00:36:29.600000
3,112113.0,2c44c80b-19ff-4c25-9706-65bae6cbfda6,101045,"{""loan_id"": 101045","""app_amount"": ""7855.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:02:57""","""duration"": 7","""merchant_id"": ""2c44c80b-19ff-4c25-9706-65bae...","""created_at"": ""2021-09-30 14:02:51""",...,"""avg_mobi_loan_principal_amount"": 9507.14","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 12450","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 2","""npa_accounts"": 2","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-30 17:16:19+00,00:33:41.800000
4,112338.0,9f68c51b-ceae-40d4-b1c2-c454bfb80e29,101044,"{""loan_id"": 101044","""app_amount"": ""3656.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 13:59:49""","""duration"": 7","""merchant_id"": ""9f68c51b-ceae-40d4-b1c2-c454b...","""created_at"": ""2021-09-30 13:59:43""",...,"""avg_mobi_loan_principal_amount"": 1500","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 1500","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}",2021-09-30 17:06:16+00,00:54:48.300000

In [45]:
df_testkyc.rename(columns = {'customer_id':'merchant_id'}, inplace = True)

In [46]:
df_testkyc.head(3)

,merchant_id,DOB,customer_date_created,channel,sub_channel,depot_name,route_name,ekyc_status
0,918bf22c-4507-4e26-8d88-464705cf6fd3,NaN,2020-12-31,Open Air,Car Vendor,Kisumu,Nyalenda,False
1,458a39da-5bd1-494b-931c-529fe9f69ae7,NaN,2021-09-28,Duka,Chemist/ Pharmacy,Kaloleni,Mathare 2,False
2,207e9b13-a5d2-4d3c-8226-10cf94d865af,1983-01-12,2019-03-19,Duka,Duka Retailer,Thika Town,Matuu,True

In [47]:
# applying merge
df_test = test.merge(df_testkyc, on ='merchant_id')

In [48]:
df_test.head()

,id,merchant_id,loan_id,loan_data,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,...,pa_closed_accounts_with_dh,created_at,updated_at,DOB,customer_date_created,channel,sub_channel,depot_name,route_name,ekyc_status
0,111915.0,40998a72-655b-48ab-be6d-5ba70c03fc6f,101051,"{""loan_id"": 101051","""app_amount"": ""1891.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 16:44:33""","""duration"": 7","""merchant_id"": ""40998a72-655b-48ab-be6d-5ba70...","""created_at"": ""2021-09-30 16:44:26""",...,"""pa_closed_accounts_with_dh"": 1}}",2021-09-30 19:56:20+00,00:33:42.100000,1986-07-12,2020-06-03,Duka,Duka Retailer,Dagoretti,Thogoto,True
1,111603.0,3a4f60b6-be62-47a9-9c81-67f3caada902,101048,"{""loan_id"": 101048","""app_amount"": ""1520.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 15:56:51""","""duration"": 7","""merchant_id"": ""3a4f60b6-be62-47a9-9c81-67f3c...","""created_at"": ""2021-09-30 15:56:45""",...,"""pa_closed_accounts_with_dh"": 1}}",2021-09-30 19:06:30+00,00:16:14.300000,1976-12-31,2020-01-11,HoReCa,Restaurant/ Cafeteria,Pack House,Kitengela 2,True
2,111703.0,c198ed2e-5383-4a11-8b4d-e0f93466fbc9,101046,"{""loan_id"": 101046","""app_amount"": ""1568.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:26:10""","""duration"": 7","""merchant_id"": ""c198ed2e-5383-4a11-8b4d-e0f93...","""created_at"": ""2021-09-30 14:26:02""",...,"""pa_closed_accounts_with_dh"": 0}}",2021-09-30 17:36:15+00,00:36:29.600000,1988-06-07,2021-06-28,Kiosk,Kiosk Retailer,Rongai,Lower Rongai,True
3,112113.0,2c44c80b-19ff-4c25-9706-65bae6cbfda6,101045,"{""loan_id"": 101045","""app_amount"": ""7855.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:02:57""","""duration"": 7","""merchant_id"": ""2c44c80b-19ff-4c25-9706-65bae...","""created_at"": ""2021-09-30 14:02:51""",...,"""pa_closed_accounts_with_dh"": 0}}",2021-09-30 17:16:19+00,00:33:41.800000,1987-07-27,2019-01-23,Duka,Duka Retailer,Embakasi,Kamulu,True
4,112338.0,9f68c51b-ceae-40d4-b1c2-c454bfb80e29,101044,"{""loan_id"": 101044","""app_amount"": ""3656.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 13:59:49""","""duration"": 7","""merchant_id"": ""9f68c51b-ceae-40d4-b1c2-c454b...","""created_at"": ""2021-09-30 13:59:43""",...,"""pa_closed_accounts_with_dh"": 0}}",2021-09-30 17:06:16+00,00:54:48.300000,1987-06-05,2020-12-14,Kiosk,Kiosk Retailer,Nakuru,Lanet,True

In [49]:
df_train.head(2)

,id,merchant_id,partner,loan_id,loan_data,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,...,avg_mobi_loan_principal_amount,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,NaN,100800,"{""loan_id"": 100800","""app_amount"": ""9160.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:22:01""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...",...,"""avg_mobi_loan_principal_amount"": 5389.89","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-27 13:36:45+00,54:44.3
1,98125.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,NaN,100339,"{""loan_id"": 100339","""app_amount"": ""8517.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-18 15:23:04""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...",...,"""avg_mobi_loan_principal_amount"": 5389.89","""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}",2021-09-18 18:36:39+00,44:39.4

In [50]:
df_test.head(2)

,id,merchant_id,loan_id,loan_data,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,...,pa_closed_accounts_with_dh,created_at,updated_at,DOB,customer_date_created,channel,sub_channel,depot_name,route_name,ekyc_status
0,111915.0,40998a72-655b-48ab-be6d-5ba70c03fc6f,101051,"{""loan_id"": 101051","""app_amount"": ""1891.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 16:44:33""","""duration"": 7","""merchant_id"": ""40998a72-655b-48ab-be6d-5ba70...","""created_at"": ""2021-09-30 16:44:26""",...,"""pa_closed_accounts_with_dh"": 1}}",2021-09-30 19:56:20+00,00:33:42.100000,1986-07-12,2020-06-03,Duka,Duka Retailer,Dagoretti,Thogoto,True
1,111603.0,3a4f60b6-be62-47a9-9c81-67f3caada902,101048,"{""loan_id"": 101048","""app_amount"": ""1520.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 15:56:51""","""duration"": 7","""merchant_id"": ""3a4f60b6-be62-47a9-9c81-67f3c...","""created_at"": ""2021-09-30 15:56:45""",...,"""pa_closed_accounts_with_dh"": 1}}",2021-09-30 19:06:30+00,00:16:14.300000,1976-12-31,2020-01-11,HoReCa,Restaurant/ Cafeteria,Pack House,Kitengela 2,True

In [51]:
df_test.columns

Index(['id', 'merchant_id', 'loan_id', 'loan_data', 'app_amount',
       'app_interest_rate', 'mpesa_time', 'duration', 'merchant_id1',
       'created_at', 'customer_id', 'loan_count', 'crb_data',
       'npa_closed_accounts', 'pa_open_accounts_with_dh',
       'pa_closed_mobi_loan_accounts_with_dh', 'npa_open_accounts',
       'pa_closed_accounts', 'pa_accounts_with_dh',
       'npa_open_mobi_loan_accounts', 'last_mobi_loan_listing_date_my_sector',
       'pa_accounts', 'pa_closed_mobi_loan_accounts',
       'last_mobi_loan_principal_amount', 'mobi_loan_accounts',
       'credit_history', 'min_mobi_loan_principal_amount',
       'avg_mobi_loan_principal_amount',
       'last_mobi_loan_listing_date_other_sectors',
       'max_mobi_loan_principal_amount', 'npa_closed_mobi_loan_accounts',
       'pa_open_accounts', 'npa_accounts',
       'pa_open_mobi_loan_accounts_with_dh', 'pa_closed_accounts_with_dh',
       'created_at', 'updated_at', 'DOB', 'customer_date_created', 'channel',
       'sub_channel', 'depot_name', 'route_name', 'ekyc_status'],
      dtype='object')

In [52]:
df_test.shape

(198, 44)

In [53]:
df_train.columns

Index(['id', 'merchant_id', 'partner', 'loan_id', 'loan_data', 'app_amount',
       'app_interest_rate', 'mpesa_time', 'duration', 'merchant_id1',
       'loan_status', 'created_at', 'customer_id', 'loan_count', 'crb_data',
       'npa_closed_accounts', 'pa_open_accounts_with_dh',
       'pa_closed_mobi_loan_accounts_with_dh', 'npa_open_accounts',
       'pa_closed_accounts', 'pa_accounts_with_dh',
       'npa_open_mobi_loan_accounts', 'last_mobi_loan_listing_date_my_sector',
       'pa_accounts', 'pa_closed_mobi_loan_accounts',
       'last_mobi_loan_principal_amount', 'mobi_loan_accounts',
       'credit_history', 'min_mobi_loan_principal_amount',
       'avg_mobi_loan_principal_amount',
       'last_mobi_loan_listing_date_other_sectors',
       'max_mobi_loan_principal_amount', 'npa_closed_mobi_loan_accounts',
       'pa_open_accounts', 'npa_accounts',
       'pa_open_mobi_loan_accounts_with_dh', 'pa_closed_accounts_with_dh',
       'created_at', 'updated_at'],
      dtype='object')

In [54]:
df_train.shape

(4226, 39)

### Check similar columns in both train and test set

In [55]:
sim_columns =[]
for x in df_train.columns:
    if x in df_test.columns:
        sim_columns.append(x)         
print(sim_columns)

['id', 'merchant_id', 'loan_id', 'loan_data', 'app_amount', 'app_interest_rate', 'mpesa_time', 'duration', 'merchant_id1', 'created_at', 'customer_id', 'loan_count', 'crb_data', 'npa_closed_accounts', 'pa_open_accounts_with_dh', 'pa_closed_mobi_loan_accounts_with_dh', 'npa_open_accounts', 'pa_closed_accounts', 'pa_accounts_with_dh', 'npa_open_mobi_loan_accounts', 'last_mobi_loan_listing_date_my_sector', 'pa_accounts', 'pa_closed_mobi_loan_accounts', 'last_mobi_loan_principal_amount', 'mobi_loan_accounts', 'credit_history', 'min_mobi_loan_principal_amount', 'avg_mobi_loan_principal_amount', 'last_mobi_loan_listing_date_other_sectors', 'max_mobi_loan_principal_amount', 'npa_closed_mobi_loan_accounts', 'pa_open_accounts', 'npa_accounts', 'pa_open_mobi_loan_accounts_with_dh', 'pa_closed_accounts_with_dh', 'created_at', 'updated_at']

In [56]:
dif_columns =[]
for col in df_test.columns:
    if col not in df_train.columns:
        dif_columns.append(col)             
print(dif_columns)

['DOB', 'customer_date_created', 'channel', 'sub_channel', 'depot_name', 'route_name', 'ekyc_status']

In [57]:
dif_co = df_test[dif_columns]

In [58]:
dif_co.head(2)

,DOB,customer_date_created,channel,sub_channel,depot_name,route_name,ekyc_status
0,1986-07-12,2020-06-03,Duka,Duka Retailer,Dagoretti,Thogoto,True
1,1976-12-31,2020-01-11,HoReCa,Restaurant/ Cafeteria,Pack House,Kitengela 2,True

In [59]:
print(len(sim_columns))

37

In [60]:
new_train = df_train[sim_columns]

In [61]:
new_train.head()

,id,merchant_id,loan_id,loan_data,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,created_at,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100800,"{""loan_id"": 100800","""app_amount"": ""9160.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:22:01""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-09-27 10:21:55""",...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}","""created_at"": ""2021-09-27 10:21:55""",2021-09-27 13:36:45+00,54:44.3
1,98125.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100339,"{""loan_id"": 100339","""app_amount"": ""8517.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-18 15:23:04""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-09-18 15:22:57""",...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}","""created_at"": ""2021-09-18 15:22:57""",2021-09-18 18:36:39+00,44:39.4
2,84249.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99723,"{""loan_id"": 99723","""app_amount"": ""7635.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-07 11:45:41""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-09-07 11:45:34""",...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}","""created_at"": ""2021-09-07 11:45:34""",2021-09-07 14:57:22+00,56:36.6
3,74877.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99359,"{""loan_id"": 99359","""app_amount"": ""7635.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-08-31 09:01:56""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-08-31 09:01:50""",...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}","""created_at"": ""2021-08-31 09:01:50""",2021-08-31 12:08:12+00,48:15.4
4,61454.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,98522,"{""loan_id"": 98522","""app_amount"": ""7635.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-08-16 08:52:59""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-08-14 09:24:20""",...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}","""created_at"": ""2021-08-14 09:24:20""",2021-08-23 12:41:30+00,50:01.1

In [62]:
new_test = df_test[sim_columns]

In [63]:
new_test.head()

,id,merchant_id,loan_id,loan_data,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,created_at,updated_at
0,111915.0,40998a72-655b-48ab-be6d-5ba70c03fc6f,101051,"{""loan_id"": 101051","""app_amount"": ""1891.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 16:44:33""","""duration"": 7","""merchant_id"": ""40998a72-655b-48ab-be6d-5ba70...","""created_at"": ""2021-09-30 16:44:26""",...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 30000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 3","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}","""created_at"": ""2021-09-30 16:44:26""",2021-09-30 19:56:20+00,00:33:42.100000
1,111603.0,3a4f60b6-be62-47a9-9c81-67f3caada902,101048,"{""loan_id"": 101048","""app_amount"": ""1520.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 15:56:51""","""duration"": 7","""merchant_id"": ""3a4f60b6-be62-47a9-9c81-67f3c...","""created_at"": ""2021-09-30 15:56:45""",...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 4000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}","""created_at"": ""2021-09-30 15:56:45""",2021-09-30 19:06:30+00,00:16:14.300000
2,111703.0,c198ed2e-5383-4a11-8b4d-e0f93466fbc9,101046,"{""loan_id"": 101046","""app_amount"": ""1568.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:26:10""","""duration"": 7","""merchant_id"": ""c198ed2e-5383-4a11-8b4d-e0f93...","""created_at"": ""2021-09-30 14:26:02""",...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 0","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}","""created_at"": ""2021-09-30 14:26:02""",2021-09-30 17:36:15+00,00:36:29.600000
3,112113.0,2c44c80b-19ff-4c25-9706-65bae6cbfda6,101045,"{""loan_id"": 101045","""app_amount"": ""7855.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:02:57""","""duration"": 7","""merchant_id"": ""2c44c80b-19ff-4c25-9706-65bae...","""created_at"": ""2021-09-30 14:02:51""",...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 12450","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 2","""npa_accounts"": 2","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}","""created_at"": ""2021-09-30 14:02:51""",2021-09-30 17:16:19+00,00:33:41.800000
4,112338.0,9f68c51b-ceae-40d4-b1c2-c454bfb80e29,101044,"{""loan_id"": 101044","""app_amount"": ""3656.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 13:59:49""","""duration"": 7","""merchant_id"": ""9f68c51b-ceae-40d4-b1c2-c454b...","""created_at"": ""2021-09-30 13:59:43""",...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 1500","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0}}","""created_at"": ""2021-09-30 13:59:43""",2021-09-30 17:06:16+00,00:54:48.300000

In [64]:
new_test.drop(['loan_data'], axis = 1, inplace = True)
new_train.drop(['loan_data'], axis = 1, inplace = True)

C:\Users\mwamb\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [65]:
new_train.head(2)

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,created_at,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,created_at,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100800,"""app_amount"": ""9160.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:22:01""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-09-27 10:21:55""",2021-09-27 13:36:45+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}","""created_at"": ""2021-09-27 10:21:55""",2021-09-27 13:36:45+00,54:44.3
1,98125.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100339,"""app_amount"": ""8517.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-18 15:23:04""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-09-18 15:22:57""",2021-09-18 18:36:39+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}","""created_at"": ""2021-09-18 15:22:57""",2021-09-18 18:36:39+00,44:39.4

In [66]:
new_test.head(2)

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,created_at,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,created_at,updated_at
0,111915.0,40998a72-655b-48ab-be6d-5ba70c03fc6f,101051,"""app_amount"": ""1891.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 16:44:33""","""duration"": 7","""merchant_id"": ""40998a72-655b-48ab-be6d-5ba70...","""created_at"": ""2021-09-30 16:44:26""",2021-09-30 19:56:20+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 30000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 3","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}","""created_at"": ""2021-09-30 16:44:26""",2021-09-30 19:56:20+00,00:33:42.100000
1,111603.0,3a4f60b6-be62-47a9-9c81-67f3caada902,101048,"""app_amount"": ""1520.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 15:56:51""","""duration"": 7","""merchant_id"": ""3a4f60b6-be62-47a9-9c81-67f3c...","""created_at"": ""2021-09-30 15:56:45""",2021-09-30 19:06:30+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 4000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1}}","""created_at"": ""2021-09-30 15:56:45""",2021-09-30 19:06:30+00,00:16:14.300000

In [67]:
new_train.columns

Index(['id', 'merchant_id', 'loan_id', 'app_amount', 'app_interest_rate',
       'mpesa_time', 'duration', 'merchant_id1', 'created_at', 'created_at',
       'customer_id', 'loan_count', 'crb_data', 'npa_closed_accounts',
       'pa_open_accounts_with_dh', 'pa_closed_mobi_loan_accounts_with_dh',
       'npa_open_accounts', 'pa_closed_accounts', 'pa_accounts_with_dh',
       'npa_open_mobi_loan_accounts', 'last_mobi_loan_listing_date_my_sector',
       'pa_accounts', 'pa_closed_mobi_loan_accounts',
       'last_mobi_loan_principal_amount', 'mobi_loan_accounts',
       'credit_history', 'min_mobi_loan_principal_amount',
       'avg_mobi_loan_principal_amount',
       'last_mobi_loan_listing_date_other_sectors',
       'max_mobi_loan_principal_amount', 'npa_closed_mobi_loan_accounts',
       'pa_open_accounts', 'npa_accounts',
       'pa_open_mobi_loan_accounts_with_dh', 'pa_closed_accounts_with_dh',
       'created_at', 'created_at', 'updated_at'],
      dtype='object')

In [68]:
new_train['pa_closed_accounts_with_dh'] = new_train['pa_closed_accounts_with_dh'].str.replace('}}',' ')
new_train['crb_data'] = new_train['crb_data'].str.replace('{',' ')
# this will replace "Boston Celtics" with "Omega Warrior"
new_train.replace(to_replace ="pa_open_mobi_loan_accounts",value =" ")

C:\Users\mwamb\AppData\Local\Temp/ipykernel_8016/391281085.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  new_train['pa_closed_accounts_with_dh'] = new_train['pa_closed_accounts_with_dh'].str.replace('}}',' ')
C:\Users\mwamb\AppData\Local\Temp/ipykernel_8016/391281085.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_train['pa_closed_accounts_with_dh'] = new_train['pa_closed_accounts_with_dh'].str.replace('}}',' ')
C:\Users\mwamb\AppData\Local\Temp/ipykernel_8016/391281085.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  new_train['crb_data'] = new_train['crb_data'].str.replace('{',' ')
C:\Users\mwamb\AppData\Local\Temp/ipykernel_8016/391281085.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_train['crb_data'] = new_train['crb_data'].str.replace('{',' ')

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,created_at,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,created_at,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100800,"""app_amount"": ""9160.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:22:01""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-09-27 10:21:55""",2021-09-27 13:36:45+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-09-27 10:21:55""",2021-09-27 13:36:45+00,54:44.3
1,98125.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100339,"""app_amount"": ""8517.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-18 15:23:04""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-09-18 15:22:57""",2021-09-18 18:36:39+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-09-18 15:22:57""",2021-09-18 18:36:39+00,44:39.4
2,84249.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99723,"""app_amount"": ""7635.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-07 11:45:41""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-09-07 11:45:34""",2021-09-07 14:57:22+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-09-07 11:45:34""",2021-09-07 14:57:22+00,56:36.6
3,74877.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99359,"""app_amount"": ""7635.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-08-31 09:01:56""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-08-31 09:01:50""",2021-08-31 12:08:12+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-08-31 09:01:50""",2021-08-31 12:08:12+00,48:15.4
4,61454.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,98522,"""app_amount"": ""7635.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-08-16 08:52:59""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-08-14 09:24:20""",2021-08-23 12:41:30+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-08-14 09:24:20""",2021-08-23 12:41:30+00,50:01.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4221,189.0,ad7f4e53-06c6-4c19-865a-5de4d9088d4a,92559,"""app_amount"": ""6870.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2020-10-12 12:22:45""","""duration"": 15","""merchant_id"": ""ad7f4e53-06c6-4c19-865a-5de4d...","""created_at"": ""2020-10-12 12:22:40""",2021-04-20 12:03:02+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""created_at"": ""2020-10-12 12:22:40""",2021-04-20 12:03:02+00,30:10.4
4222,231.0,959ab23f-9d52-4d90-b15b-101048abd61f,92449,"""app_amount"": ""1384.00""","""app_interest_rate"": ""9.00""","""mpesa_time"": ""2020-10-02 05:59:21""","""duration"": 15","""merchant_id"": ""959ab23f-9d52-4d90-b15b-10104...","""created_at"": ""2020-10-02 05:59:16""",2021-04-20 12:00:02+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 1000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2020-10-02 05:59:16""",2021-04-20 12:00:02+00,30:09.1
4223,161.0,a775435d-d999-424e-9181-bfe55902b6e7,92452,"""app_amount"": ""1500.00""","""app_interest_rate"": ""9.00""","""mpesa_time"": ""2020-10-02 07:53:38""","""duration"": 15","""merchant_id"": ""a775435d-d999-424e-9181-bfe55...","""created_at"": ""2020-10-02 07:53:33""",2021-04-20 12:00:02+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 0","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2020-10-02 07:53:33""",2021-04-20 12:00:02+00,30:09.5
4224,339.0,bb1cfb08-bd30-4870-b0ba-a45222961769,92415,"""app_amount"": ""9000.00""","""app_interest_rate"": ""10.80""","""mpesa_time"": ""2020-09-30 10:39:30""","""duration"": 15","""merchant_id"": ""bb1cfb08-bd30-4870-b0ba-a4522...","""created_at"": ""2020-09-30 10:39:25""",2021-04-20 11:57:05+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 1430","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2020-09-30 10:39:25""",2021-04-20 11:57:05+00,45:12.7
4225,294.0,5d1df13b-ae7d-4ade-b2dc-92793f4add82,92212,"""app_amount"": ""813.00""","""app_interest_rate"": ""22.50""","""mpesa_time"": ""2020-09-17 08:23:48""","""duration"": 15","""merchant_id"": ""5d1df13b-ae7d-4ade-b2dc-92793...","""created_at"": ""2020-09-17 08:23:42""",2021-04-20 11:54:01+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 2400","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2020-09-17 08:23:42""",2021-04-20 11:54:01+00,30:06.9

In [69]:
new_test['pa_closed_accounts_with_dh'] = new_test['pa_closed_accounts_with_dh'].str.replace('}}',' ')
new_test['crb_data'] = new_test['crb_data'].str.replace('{',' ')
new_test.replace(to_replace ="pa_open_mobi_loan_accounts",value =" ")

C:\Users\mwamb\AppData\Local\Temp/ipykernel_8016/1188256417.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  new_test['pa_closed_accounts_with_dh'] = new_test['pa_closed_accounts_with_dh'].str.replace('}}',' ')
C:\Users\mwamb\AppData\Local\Temp/ipykernel_8016/1188256417.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_test['pa_closed_accounts_with_dh'] = new_test['pa_closed_accounts_with_dh'].str.replace('}}',' ')
C:\Users\mwamb\AppData\Local\Temp/ipykernel_8016/1188256417.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  new_test['crb_data'] = new_test['crb_data'].str.replace('{',' ')
C:\Users\mwamb\AppData\Local\Temp/ipykernel_8016/1188256417.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_test['crb_data'] = new_test['crb_data'].str.replace('{',' ')

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,created_at,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,created_at,updated_at
0,111915.0,40998a72-655b-48ab-be6d-5ba70c03fc6f,101051,"""app_amount"": ""1891.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 16:44:33""","""duration"": 7","""merchant_id"": ""40998a72-655b-48ab-be6d-5ba70...","""created_at"": ""2021-09-30 16:44:26""",2021-09-30 19:56:20+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 30000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 3","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-09-30 16:44:26""",2021-09-30 19:56:20+00,00:33:42.100000
1,111603.0,3a4f60b6-be62-47a9-9c81-67f3caada902,101048,"""app_amount"": ""1520.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 15:56:51""","""duration"": 7","""merchant_id"": ""3a4f60b6-be62-47a9-9c81-67f3c...","""created_at"": ""2021-09-30 15:56:45""",2021-09-30 19:06:30+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 4000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-09-30 15:56:45""",2021-09-30 19:06:30+00,00:16:14.300000
2,111703.0,c198ed2e-5383-4a11-8b4d-e0f93466fbc9,101046,"""app_amount"": ""1568.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:26:10""","""duration"": 7","""merchant_id"": ""c198ed2e-5383-4a11-8b4d-e0f93...","""created_at"": ""2021-09-30 14:26:02""",2021-09-30 17:36:15+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 0","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2021-09-30 14:26:02""",2021-09-30 17:36:15+00,00:36:29.600000
3,112113.0,2c44c80b-19ff-4c25-9706-65bae6cbfda6,101045,"""app_amount"": ""7855.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:02:57""","""duration"": 7","""merchant_id"": ""2c44c80b-19ff-4c25-9706-65bae...","""created_at"": ""2021-09-30 14:02:51""",2021-09-30 17:16:19+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 12450","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 2","""npa_accounts"": 2","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2021-09-30 14:02:51""",2021-09-30 17:16:19+00,00:33:41.800000
4,112338.0,9f68c51b-ceae-40d4-b1c2-c454bfb80e29,101044,"""app_amount"": ""3656.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 13:59:49""","""duration"": 7","""merchant_id"": ""9f68c51b-ceae-40d4-b1c2-c454b...","""created_at"": ""2021-09-30 13:59:43""",2021-09-30 17:06:16+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 1500","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2021-09-30 13:59:43""",2021-09-30 17:06:16+00,00:54:48.300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,107768.0,baea2304-3bfa-4a51-890c-9cef9c2beb31,100808,"""app_amount"": ""1100.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:58:34""","""duration"": 7","""merchant_id"": ""baea2304-3bfa-4a51-890c-9cef9...","""created_at"": ""2021-09-27 10:58:27""",2021-09-27 14:06:21+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 0","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2021-09-27 10:58:27""",2021-09-27 14:06:21+00,00:34:46.700000
194,107752.0,d042c09b-335a-4ae2-84d1-3ba5de3d259f,100806,"""app_amount"": ""5340.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:54:05""","""duration"": 7","""merchant_id"": ""d042c09b-335a-4ae2-84d1-3ba5d...","""created_at"": ""2021-09-27 10:53:58""",2021-09-27 14:06:20+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 2000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2021-09-27 10:53:58""",2021-09-27 14:06:20+00,00:24:29.600000
195,107704.0,ad9d0cba-f430-46e0-b1ed-d47e7d301073,100803,"""app_amount"": ""4077.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:42:29""","""duration"": 7","""merchant_id"": ""ad9d0cba-f430-46e0-b1ed-d47e7...","""created_at"": ""2021-09-27 10:42:24""",2021-09-27 13:56:35+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 30000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 3","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2021-09-27 10:42:24""",2021-09-27 13:56:35+00,00:05:41.100000
196,107731.0,eb24a127-d938-443b-b94e-e4b7db28be35,100805,"""app_amount"": ""38431.00""","""app_interest_rate"": ""0.50""","""mpesa_time"": ""2021-09-27 10:43:49""","""duration"": 7","""merchant_id"": ""eb24a127-d938-443b-b94e-e4b7d...","""created_at"": ""2021-09-27 10:43:44""",2021-09-27 13:56:35+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 1920","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2021-09-27 10:43:44""",2021-09-27 13:56:35+00,00:45:04.900000
197,107430.0,4f7cec89-ba9d-4929-8e9d-80d63c846174,100804,"""app_amount"": ""4780.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:43:01""","""duration"": 7","""merchant_id"": ""4f7cec89-ba9d-4929-8e9d-80d63...","""created_at"": ""2021-09-27 10:42:55""",2021-09-27 13:56:35+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 5000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2021-09-27 10:42:55""",2021-09-27 13:56:35+00,00:04:30.200000

In [70]:
new_train.head()

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,created_at,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,created_at,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100800,"""app_amount"": ""9160.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-27 10:22:01""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-09-27 10:21:55""",2021-09-27 13:36:45+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-09-27 10:21:55""",2021-09-27 13:36:45+00,54:44.3
1,98125.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100339,"""app_amount"": ""8517.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-18 15:23:04""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-09-18 15:22:57""",2021-09-18 18:36:39+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-09-18 15:22:57""",2021-09-18 18:36:39+00,44:39.4
2,84249.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99723,"""app_amount"": ""7635.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-07 11:45:41""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-09-07 11:45:34""",2021-09-07 14:57:22+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-09-07 11:45:34""",2021-09-07 14:57:22+00,56:36.6
3,74877.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99359,"""app_amount"": ""7635.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-08-31 09:01:56""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-08-31 09:01:50""",2021-08-31 12:08:12+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-08-31 09:01:50""",2021-08-31 12:08:12+00,48:15.4
4,61454.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,98522,"""app_amount"": ""7635.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-08-16 08:52:59""","""duration"": 7","""merchant_id"": ""56cebec0-3bf6-43a8-bf32-66bb6...","""created_at"": ""2021-08-14 09:24:20""",2021-08-23 12:41:30+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 6000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-08-14 09:24:20""",2021-08-23 12:41:30+00,50:01.1

In [71]:
new_test.head()

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,created_at,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,created_at,updated_at
0,111915.0,40998a72-655b-48ab-be6d-5ba70c03fc6f,101051,"""app_amount"": ""1891.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 16:44:33""","""duration"": 7","""merchant_id"": ""40998a72-655b-48ab-be6d-5ba70...","""created_at"": ""2021-09-30 16:44:26""",2021-09-30 19:56:20+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 30000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 3","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-09-30 16:44:26""",2021-09-30 19:56:20+00,00:33:42.100000
1,111603.0,3a4f60b6-be62-47a9-9c81-67f3caada902,101048,"""app_amount"": ""1520.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 15:56:51""","""duration"": 7","""merchant_id"": ""3a4f60b6-be62-47a9-9c81-67f3c...","""created_at"": ""2021-09-30 15:56:45""",2021-09-30 19:06:30+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 4000","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 1","""created_at"": ""2021-09-30 15:56:45""",2021-09-30 19:06:30+00,00:16:14.300000
2,111703.0,c198ed2e-5383-4a11-8b4d-e0f93466fbc9,101046,"""app_amount"": ""1568.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:26:10""","""duration"": 7","""merchant_id"": ""c198ed2e-5383-4a11-8b4d-e0f93...","""created_at"": ""2021-09-30 14:26:02""",2021-09-30 17:36:15+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 0","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 1","""npa_accounts"": 0","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2021-09-30 14:26:02""",2021-09-30 17:36:15+00,00:36:29.600000
3,112113.0,2c44c80b-19ff-4c25-9706-65bae6cbfda6,101045,"""app_amount"": ""7855.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 14:02:57""","""duration"": 7","""merchant_id"": ""2c44c80b-19ff-4c25-9706-65bae...","""created_at"": ""2021-09-30 14:02:51""",2021-09-30 17:16:19+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 12450","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 2","""npa_accounts"": 2","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2021-09-30 14:02:51""",2021-09-30 17:16:19+00,00:33:41.800000
4,112338.0,9f68c51b-ceae-40d4-b1c2-c454bfb80e29,101044,"""app_amount"": ""3656.00""","""app_interest_rate"": ""0.90""","""mpesa_time"": ""2021-09-30 13:59:49""","""duration"": 7","""merchant_id"": ""9f68c51b-ceae-40d4-b1c2-c454b...","""created_at"": ""2021-09-30 13:59:43""",2021-09-30 17:06:16+00,...,"""last_mobi_loan_listing_date_other_sectors"": ...","""max_mobi_loan_principal_amount"": 1500","""npa_closed_mobi_loan_accounts"": 0","""pa_open_accounts"": 0","""npa_accounts"": 1","""pa_open_mobi_loan_accounts_with_dh"": 0","""pa_closed_accounts_with_dh"": 0","""created_at"": ""2021-09-30 13:59:43""",2021-09-30 17:06:16+00,00:54:48.300000

In [72]:
ColT= new_train.columns[3:-2]
print(ColT)

Index(['app_amount', 'app_interest_rate', 'mpesa_time', 'duration',
       'merchant_id1', 'created_at', 'created_at', 'customer_id', 'loan_count',
       'crb_data', 'npa_closed_accounts', 'pa_open_accounts_with_dh',
       'pa_closed_mobi_loan_accounts_with_dh', 'npa_open_accounts',
       'pa_closed_accounts', 'pa_accounts_with_dh',
       'npa_open_mobi_loan_accounts', 'last_mobi_loan_listing_date_my_sector',
       'pa_accounts', 'pa_closed_mobi_loan_accounts',
       'last_mobi_loan_principal_amount', 'mobi_loan_accounts',
       'credit_history', 'min_mobi_loan_principal_amount',
       'avg_mobi_loan_principal_amount',
       'last_mobi_loan_listing_date_other_sectors',
       'max_mobi_loan_principal_amount', 'npa_closed_mobi_loan_accounts',
       'pa_open_accounts', 'npa_accounts',
       'pa_open_mobi_loan_accounts_with_dh', 'pa_closed_accounts_with_dh',
       'created_at'],
      dtype='object')

In [73]:
# remove_words = ['app_amount', 'app_interest_rate', 'mpesa_time', 'duration',
#        'merchant_id1', 'created_at', 'created_at', 'customer_id', 'loan_count',
#        'crb_data', 'npa_closed_accounts', 'pa_open_accounts_with_dh',
#        'pa_closed_mobi_loan_accounts_with_dh', 'npa_open_accounts',
#        'pa_closed_accounts', 'pa_accounts_with_dh',
#        'npa_open_mobi_loan_accounts', 'last_mobi_loan_listing_date_my_sector',
#        'pa_accounts', 'pa_closed_mobi_loan_accounts',
#        'last_mobi_loan_principal_amount', 'mobi_loan_accounts',
#        'credit_history', 'min_mobi_loan_principal_amount',
#        'avg_mobi_loan_principal_amount',
#        'last_mobi_loan_listing_date_other_sectors',
#        'max_mobi_loan_principal_amount', 'npa_closed_mobi_loan_accounts',
#        'pa_open_accounts', 'npa_accounts',
#        'pa_open_mobi_loan_accounts_with_dh', 'pa_closed_accounts_with_dh',
#        'created_at']

In [74]:
new_train.replace(to_replace ='"', value = ' ', inplace = True, regex = True)
new_test.replace(to_replace ='"', value = ' ', inplace = True, regex = True)

C:\Users\mwamb\anaconda3\lib\site-packages\pandas\core\frame.py:4524: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [75]:
new_train.head(2)

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,created_at,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,created_at,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100800,app_amount : 9160.00,app_interest_rate : 0.90,mpesa_time : 2021-09-27 10:22:01,duration : 7,merchant_id : 56cebec0-3bf6-43a8-bf32-66bb6...,created_at : 2021-09-27 10:21:55,2021-09-27 13:36:45+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 6000,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 0,npa_accounts : 1,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 1,created_at : 2021-09-27 10:21:55,2021-09-27 13:36:45+00,54:44.3
1,98125.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100339,app_amount : 8517.00,app_interest_rate : 0.90,mpesa_time : 2021-09-18 15:23:04,duration : 7,merchant_id : 56cebec0-3bf6-43a8-bf32-66bb6...,created_at : 2021-09-18 15:22:57,2021-09-18 18:36:39+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 6000,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 0,npa_accounts : 1,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 1,created_at : 2021-09-18 15:22:57,2021-09-18 18:36:39+00,44:39.4

In [76]:
new_train.columns

Index(['id', 'merchant_id', 'loan_id', 'app_amount', 'app_interest_rate',
       'mpesa_time', 'duration', 'merchant_id1', 'created_at', 'created_at',
       'customer_id', 'loan_count', 'crb_data', 'npa_closed_accounts',
       'pa_open_accounts_with_dh', 'pa_closed_mobi_loan_accounts_with_dh',
       'npa_open_accounts', 'pa_closed_accounts', 'pa_accounts_with_dh',
       'npa_open_mobi_loan_accounts', 'last_mobi_loan_listing_date_my_sector',
       'pa_accounts', 'pa_closed_mobi_loan_accounts',
       'last_mobi_loan_principal_amount', 'mobi_loan_accounts',
       'credit_history', 'min_mobi_loan_principal_amount',
       'avg_mobi_loan_principal_amount',
       'last_mobi_loan_listing_date_other_sectors',
       'max_mobi_loan_principal_amount', 'npa_closed_mobi_loan_accounts',
       'pa_open_accounts', 'npa_accounts',
       'pa_open_mobi_loan_accounts_with_dh', 'pa_closed_accounts_with_dh',
       'created_at', 'created_at', 'updated_at'],
      dtype='object')

In [77]:
new_test.columns

Index(['id', 'merchant_id', 'loan_id', 'app_amount', 'app_interest_rate',
       'mpesa_time', 'duration', 'merchant_id1', 'created_at', 'created_at',
       'customer_id', 'loan_count', 'crb_data', 'npa_closed_accounts',
       'pa_open_accounts_with_dh', 'pa_closed_mobi_loan_accounts_with_dh',
       'npa_open_accounts', 'pa_closed_accounts', 'pa_accounts_with_dh',
       'npa_open_mobi_loan_accounts', 'last_mobi_loan_listing_date_my_sector',
       'pa_accounts', 'pa_closed_mobi_loan_accounts',
       'last_mobi_loan_principal_amount', 'mobi_loan_accounts',
       'credit_history', 'min_mobi_loan_principal_amount',
       'avg_mobi_loan_principal_amount',
       'last_mobi_loan_listing_date_other_sectors',
       'max_mobi_loan_principal_amount', 'npa_closed_mobi_loan_accounts',
       'pa_open_accounts', 'npa_accounts',
       'pa_open_mobi_loan_accounts_with_dh', 'pa_closed_accounts_with_dh',
       'created_at', 'created_at', 'updated_at'],
      dtype='object')

In [78]:
new_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4226 entries, 0 to 4225
Data columns (total 38 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   id                                         4226 non-null   float64
 1   merchant_id                                4226 non-null   object
 2   loan_id                                    4226 non-null   int64
 3   app_amount                                 4226 non-null   object
 4   app_interest_rate                          4226 non-null   object
 5   mpesa_time                                 4226 non-null   object
 6   duration                                   4226 non-null   object
 7   merchant_id1                               4226 non-null   object
 8   created_at                                 4226 non-null   object
 9   created_at                                 4226 non-null   object
 10  customer_id                                4226 non-null   object
 11  loan_count                                 4226 non-null   object
 12  crb_data                                   4226 non-null   object
 13  npa_closed_accounts                        4118 non-null   object
 14  pa_open_accounts_with_dh                   4118 non-null   object
 15  pa_closed_mobi_loan_accounts_with_dh       4118 non-null   object
 16  npa_open_accounts                          4118 non-null   object
 17  pa_closed_accounts                         4118 non-null   object
 18  pa_accounts_with_dh                        4118 non-null   object
 19  npa_open_mobi_loan_accounts                4118 non-null   object
 20  last_mobi_loan_listing_date_my_sector      4118 non-null   object
 21  pa_accounts                                4118 non-null   object
 22  pa_closed_mobi_loan_accounts               4118 non-null   object
 23  last_mobi_loan_principal_amount            4118 non-null   object
 24  mobi_loan_accounts                         4118 non-null   object
 25  credit_history                             4118 non-null   object
 26  min_mobi_loan_principal_amount             4118 non-null   object
 27  avg_mobi_loan_principal_amount             4118 non-null   object
 28  last_mobi_loan_listing_date_other_sectors  4118 non-null   object
 29  max_mobi_loan_principal_amount             4118 non-null   object
 30  npa_closed_mobi_loan_accounts              4118 non-null   object
 31  pa_open_accounts                           4118 non-null   object
 32  npa_accounts                               4118 non-null   object
 33  pa_open_mobi_loan_accounts_with_dh         4118 non-null   object
 34  pa_closed_accounts_with_dh                 4118 non-null   object
 35  created_at                                 4226 non-null   object
 36  created_at                                 4226 non-null   object
 37  updated_at                                 4211 non-null   object
dtypes: float64(1), int64(1), object(36)
memory usage: 1.3+ MB

In [79]:
new_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 198 entries, 0 to 197
Data columns (total 38 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   id                                         198 non-null    float64
 1   merchant_id                                198 non-null    object
 2   loan_id                                    198 non-null    int64
 3   app_amount                                 198 non-null    object
 4   app_interest_rate                          198 non-null    object
 5   mpesa_time                                 198 non-null    object
 6   duration                                   198 non-null    object
 7   merchant_id1                               198 non-null    object
 8   created_at                                 198 non-null    object
 9   created_at                                 198 non-null    object
 10  customer_id                                198 non-null    object
 11  loan_count                                 198 non-null    object
 12  crb_data                                   198 non-null    object
 13  npa_closed_accounts                        197 non-null    object
 14  pa_open_accounts_with_dh                   197 non-null    object
 15  pa_closed_mobi_loan_accounts_with_dh       197 non-null    object
 16  npa_open_accounts                          197 non-null    object
 17  pa_closed_accounts                         197 non-null    object
 18  pa_accounts_with_dh                        197 non-null    object
 19  npa_open_mobi_loan_accounts                197 non-null    object
 20  last_mobi_loan_listing_date_my_sector      197 non-null    object
 21  pa_accounts                                197 non-null    object
 22  pa_closed_mobi_loan_accounts               197 non-null    object
 23  last_mobi_loan_principal_amount            197 non-null    object
 24  mobi_loan_accounts                         197 non-null    object
 25  credit_history                             197 non-null    object
 26  min_mobi_loan_principal_amount             197 non-null    object
 27  avg_mobi_loan_principal_amount             197 non-null    object
 28  last_mobi_loan_listing_date_other_sectors  197 non-null    object
 29  max_mobi_loan_principal_amount             197 non-null    object
 30  npa_closed_mobi_loan_accounts              197 non-null    object
 31  pa_open_accounts                           197 non-null    object
 32  npa_accounts                               197 non-null    object
 33  pa_open_mobi_loan_accounts_with_dh         197 non-null    object
 34  pa_closed_accounts_with_dh                 197 non-null    object
 35  created_at                                 198 non-null    object
 36  created_at                                 198 non-null    object
 37  updated_at                                 198 non-null    object
dtypes: float64(1), int64(1), object(36)
memory usage: 60.3+ KB

In [80]:
new_train.head()

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,created_at,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,created_at,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100800,app_amount : 9160.00,app_interest_rate : 0.90,mpesa_time : 2021-09-27 10:22:01,duration : 7,merchant_id : 56cebec0-3bf6-43a8-bf32-66bb6...,created_at : 2021-09-27 10:21:55,2021-09-27 13:36:45+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 6000,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 0,npa_accounts : 1,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 1,created_at : 2021-09-27 10:21:55,2021-09-27 13:36:45+00,54:44.3
1,98125.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100339,app_amount : 8517.00,app_interest_rate : 0.90,mpesa_time : 2021-09-18 15:23:04,duration : 7,merchant_id : 56cebec0-3bf6-43a8-bf32-66bb6...,created_at : 2021-09-18 15:22:57,2021-09-18 18:36:39+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 6000,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 0,npa_accounts : 1,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 1,created_at : 2021-09-18 15:22:57,2021-09-18 18:36:39+00,44:39.4
2,84249.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99723,app_amount : 7635.00,app_interest_rate : 0.90,mpesa_time : 2021-09-07 11:45:41,duration : 7,merchant_id : 56cebec0-3bf6-43a8-bf32-66bb6...,created_at : 2021-09-07 11:45:34,2021-09-07 14:57:22+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 6000,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 0,npa_accounts : 1,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 1,created_at : 2021-09-07 11:45:34,2021-09-07 14:57:22+00,56:36.6
3,74877.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99359,app_amount : 7635.00,app_interest_rate : 0.90,mpesa_time : 2021-08-31 09:01:56,duration : 7,merchant_id : 56cebec0-3bf6-43a8-bf32-66bb6...,created_at : 2021-08-31 09:01:50,2021-08-31 12:08:12+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 6000,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 0,npa_accounts : 1,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 1,created_at : 2021-08-31 09:01:50,2021-08-31 12:08:12+00,48:15.4
4,61454.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,98522,app_amount : 7635.00,app_interest_rate : 0.90,mpesa_time : 2021-08-16 08:52:59,duration : 7,merchant_id : 56cebec0-3bf6-43a8-bf32-66bb6...,created_at : 2021-08-14 09:24:20,2021-08-23 12:41:30+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 6000,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 0,npa_accounts : 1,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 1,created_at : 2021-08-14 09:24:20,2021-08-23 12:41:30+00,50:01.1

In [81]:
new_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4226 entries, 0 to 4225
Data columns (total 38 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   id                                         4226 non-null   float64
 1   merchant_id                                4226 non-null   object
 2   loan_id                                    4226 non-null   int64
 3   app_amount                                 4226 non-null   object
 4   app_interest_rate                          4226 non-null   object
 5   mpesa_time                                 4226 non-null   object
 6   duration                                   4226 non-null   object
 7   merchant_id1                               4226 non-null   object
 8   created_at                                 4226 non-null   object
 9   created_at                                 4226 non-null   object
 10  customer_id                                4226 non-null   object
 11  loan_count                                 4226 non-null   object
 12  crb_data                                   4226 non-null   object
 13  npa_closed_accounts                        4118 non-null   object
 14  pa_open_accounts_with_dh                   4118 non-null   object
 15  pa_closed_mobi_loan_accounts_with_dh       4118 non-null   object
 16  npa_open_accounts                          4118 non-null   object
 17  pa_closed_accounts                         4118 non-null   object
 18  pa_accounts_with_dh                        4118 non-null   object
 19  npa_open_mobi_loan_accounts                4118 non-null   object
 20  last_mobi_loan_listing_date_my_sector      4118 non-null   object
 21  pa_accounts                                4118 non-null   object
 22  pa_closed_mobi_loan_accounts               4118 non-null   object
 23  last_mobi_loan_principal_amount            4118 non-null   object
 24  mobi_loan_accounts                         4118 non-null   object
 25  credit_history                             4118 non-null   object
 26  min_mobi_loan_principal_amount             4118 non-null   object
 27  avg_mobi_loan_principal_amount             4118 non-null   object
 28  last_mobi_loan_listing_date_other_sectors  4118 non-null   object
 29  max_mobi_loan_principal_amount             4118 non-null   object
 30  npa_closed_mobi_loan_accounts              4118 non-null   object
 31  pa_open_accounts                           4118 non-null   object
 32  npa_accounts                               4118 non-null   object
 33  pa_open_mobi_loan_accounts_with_dh         4118 non-null   object
 34  pa_closed_accounts_with_dh                 4118 non-null   object
 35  created_at                                 4226 non-null   object
 36  created_at                                 4226 non-null   object
 37  updated_at                                 4211 non-null   object
dtypes: float64(1), int64(1), object(36)
memory usage: 1.3+ MB

In [82]:
new_train.head(2)

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at,created_at,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at,created_at,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100800,app_amount : 9160.00,app_interest_rate : 0.90,mpesa_time : 2021-09-27 10:22:01,duration : 7,merchant_id : 56cebec0-3bf6-43a8-bf32-66bb6...,created_at : 2021-09-27 10:21:55,2021-09-27 13:36:45+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 6000,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 0,npa_accounts : 1,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 1,created_at : 2021-09-27 10:21:55,2021-09-27 13:36:45+00,54:44.3
1,98125.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100339,app_amount : 8517.00,app_interest_rate : 0.90,mpesa_time : 2021-09-18 15:23:04,duration : 7,merchant_id : 56cebec0-3bf6-43a8-bf32-66bb6...,created_at : 2021-09-18 15:22:57,2021-09-18 18:36:39+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 6000,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 0,npa_accounts : 1,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 1,created_at : 2021-09-18 15:22:57,2021-09-18 18:36:39+00,44:39.4

In [83]:
new_train.columns = ['id', 'merchant_id', 'loan_id', 'app_amount', 'app_interest_rate',
       'mpesa_time', 'duration', 'merchant_id1', 'created_at1', 'created_at2',
       'customer_id', 'loan_count', 'crb_data', 'npa_closed_accounts',
       'pa_open_accounts_with_dh', 'pa_closed_mobi_loan_accounts_with_dh',
       'npa_open_accounts', 'pa_closed_accounts', 'pa_accounts_with_dh',
       'npa_open_mobi_loan_accounts', 'last_mobi_loan_listing_date_my_sector',
       'pa_accounts', 'pa_closed_mobi_loan_accounts',
       'last_mobi_loan_principal_amount', 'mobi_loan_accounts',
       'credit_history', 'min_mobi_loan_principal_amount',
       'avg_mobi_loan_principal_amount',
       'last_mobi_loan_listing_date_other_sectors',
       'max_mobi_loan_principal_amount', 'npa_closed_mobi_loan_accounts',
       'pa_open_accounts', 'npa_accounts',
       'pa_open_mobi_loan_accounts_with_dh', 'pa_closed_accounts_with_dh',
       'created_at3', 'created_at4', 'updated_at']

In [84]:
new_test.columns = ['id', 'merchant_id', 'loan_id', 'app_amount', 'app_interest_rate',
       'mpesa_time', 'duration', 'merchant_id1', 'created_at1', 'created_at2',
       'customer_id', 'loan_count', 'crb_data', 'npa_closed_accounts',
       'pa_open_accounts_with_dh', 'pa_closed_mobi_loan_accounts_with_dh',
       'npa_open_accounts', 'pa_closed_accounts', 'pa_accounts_with_dh',
       'npa_open_mobi_loan_accounts', 'last_mobi_loan_listing_date_my_sector',
       'pa_accounts', 'pa_closed_mobi_loan_accounts',
       'last_mobi_loan_principal_amount', 'mobi_loan_accounts',
       'credit_history', 'min_mobi_loan_principal_amount',
       'avg_mobi_loan_principal_amount',
       'last_mobi_loan_listing_date_other_sectors',
       'max_mobi_loan_principal_amount', 'npa_closed_mobi_loan_accounts',
       'pa_open_accounts', 'npa_accounts',
       'pa_open_mobi_loan_accounts_with_dh', 'pa_closed_accounts_with_dh',
       'created_at3', 'created_at4', 'updated_at']

In [85]:
new_train = new_train.iloc[:,~new_train.columns.duplicated()]
new_test = new_test.iloc[:,~new_test.columns.duplicated()]

In [86]:
new_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4226 entries, 0 to 4225
Data columns (total 38 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   id                                         4226 non-null   float64
 1   merchant_id                                4226 non-null   object
 2   loan_id                                    4226 non-null   int64
 3   app_amount                                 4226 non-null   object
 4   app_interest_rate                          4226 non-null   object
 5   mpesa_time                                 4226 non-null   object
 6   duration                                   4226 non-null   object
 7   merchant_id1                               4226 non-null   object
 8   created_at1                                4226 non-null   object
 9   created_at2                                4226 non-null   object
 10  customer_id                                4226 non-null   object
 11  loan_count                                 4226 non-null   object
 12  crb_data                                   4226 non-null   object
 13  npa_closed_accounts                        4118 non-null   object
 14  pa_open_accounts_with_dh                   4118 non-null   object
 15  pa_closed_mobi_loan_accounts_with_dh       4118 non-null   object
 16  npa_open_accounts                          4118 non-null   object
 17  pa_closed_accounts                         4118 non-null   object
 18  pa_accounts_with_dh                        4118 non-null   object
 19  npa_open_mobi_loan_accounts                4118 non-null   object
 20  last_mobi_loan_listing_date_my_sector      4118 non-null   object
 21  pa_accounts                                4118 non-null   object
 22  pa_closed_mobi_loan_accounts               4118 non-null   object
 23  last_mobi_loan_principal_amount            4118 non-null   object
 24  mobi_loan_accounts                         4118 non-null   object
 25  credit_history                             4118 non-null   object
 26  min_mobi_loan_principal_amount             4118 non-null   object
 27  avg_mobi_loan_principal_amount             4118 non-null   object
 28  last_mobi_loan_listing_date_other_sectors  4118 non-null   object
 29  max_mobi_loan_principal_amount             4118 non-null   object
 30  npa_closed_mobi_loan_accounts              4118 non-null   object
 31  pa_open_accounts                           4118 non-null   object
 32  npa_accounts                               4118 non-null   object
 33  pa_open_mobi_loan_accounts_with_dh         4118 non-null   object
 34  pa_closed_accounts_with_dh                 4118 non-null   object
 35  created_at3                                4226 non-null   object
 36  created_at4                                4226 non-null   object
 37  updated_at                                 4211 non-null   object
dtypes: float64(1), int64(1), object(36)
memory usage: 1.3+ MB

In [87]:
# for i in new_train.iloc[:,3:-1]:
#     new_train[i] = new_train[i].str.split(": ").str[1]

In [88]:
# for i in new_test.iloc[:,3:-1]:
#     new_test[i] = new_test[i].str.split(": ").str[1]

In [89]:
new_train.tail()

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at1,created_at2,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at3,created_at4,updated_at
4221,189.0,ad7f4e53-06c6-4c19-865a-5de4d9088d4a,92559,app_amount : 6870.00,app_interest_rate : 0.90,mpesa_time : 2020-10-12 12:22:45,duration : 15,merchant_id : ad7f4e53-06c6-4c19-865a-5de4d...,created_at : 2020-10-12 12:22:40,2021-04-20 12:03:02+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,created_at : 2020-10-12 12:22:40,2021-04-20 12:03:02+00,30:10.4
4222,231.0,959ab23f-9d52-4d90-b15b-101048abd61f,92449,app_amount : 1384.00,app_interest_rate : 9.00,mpesa_time : 2020-10-02 05:59:21,duration : 15,merchant_id : 959ab23f-9d52-4d90-b15b-10104...,created_at : 2020-10-02 05:59:16,2021-04-20 12:00:02+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 1000,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 1,npa_accounts : 0,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 0,created_at : 2020-10-02 05:59:16,2021-04-20 12:00:02+00,30:09.1
4223,161.0,a775435d-d999-424e-9181-bfe55902b6e7,92452,app_amount : 1500.00,app_interest_rate : 9.00,mpesa_time : 2020-10-02 07:53:38,duration : 15,merchant_id : a775435d-d999-424e-9181-bfe55...,created_at : 2020-10-02 07:53:33,2021-04-20 12:00:02+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 0,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 1,npa_accounts : 0,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 0,created_at : 2020-10-02 07:53:33,2021-04-20 12:00:02+00,30:09.5
4224,339.0,bb1cfb08-bd30-4870-b0ba-a45222961769,92415,app_amount : 9000.00,app_interest_rate : 10.80,mpesa_time : 2020-09-30 10:39:30,duration : 15,merchant_id : bb1cfb08-bd30-4870-b0ba-a4522...,created_at : 2020-09-30 10:39:25,2021-04-20 11:57:05+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 1430,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 0,npa_accounts : 0,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 0,created_at : 2020-09-30 10:39:25,2021-04-20 11:57:05+00,45:12.7
4225,294.0,5d1df13b-ae7d-4ade-b2dc-92793f4add82,92212,app_amount : 813.00,app_interest_rate : 22.50,mpesa_time : 2020-09-17 08:23:48,duration : 15,merchant_id : 5d1df13b-ae7d-4ade-b2dc-92793...,created_at : 2020-09-17 08:23:42,2021-04-20 11:54:01+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 2400,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 0,npa_accounts : 1,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 0,created_at : 2020-09-17 08:23:42,2021-04-20 11:54:01+00,30:06.9

In [90]:
new_test.head()

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at1,created_at2,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at3,created_at4,updated_at
0,111915.0,40998a72-655b-48ab-be6d-5ba70c03fc6f,101051,app_amount : 1891.00,app_interest_rate : 0.90,mpesa_time : 2021-09-30 16:44:33,duration : 7,merchant_id : 40998a72-655b-48ab-be6d-5ba70...,created_at : 2021-09-30 16:44:26,2021-09-30 19:56:20+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 30000,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 1,npa_accounts : 3,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 1,created_at : 2021-09-30 16:44:26,2021-09-30 19:56:20+00,00:33:42.100000
1,111603.0,3a4f60b6-be62-47a9-9c81-67f3caada902,101048,app_amount : 1520.00,app_interest_rate : 0.90,mpesa_time : 2021-09-30 15:56:51,duration : 7,merchant_id : 3a4f60b6-be62-47a9-9c81-67f3c...,created_at : 2021-09-30 15:56:45,2021-09-30 19:06:30+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 4000,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 1,npa_accounts : 0,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 1,created_at : 2021-09-30 15:56:45,2021-09-30 19:06:30+00,00:16:14.300000
2,111703.0,c198ed2e-5383-4a11-8b4d-e0f93466fbc9,101046,app_amount : 1568.00,app_interest_rate : 0.90,mpesa_time : 2021-09-30 14:26:10,duration : 7,merchant_id : c198ed2e-5383-4a11-8b4d-e0f93...,created_at : 2021-09-30 14:26:02,2021-09-30 17:36:15+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 0,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 1,npa_accounts : 0,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 0,created_at : 2021-09-30 14:26:02,2021-09-30 17:36:15+00,00:36:29.600000
3,112113.0,2c44c80b-19ff-4c25-9706-65bae6cbfda6,101045,app_amount : 7855.00,app_interest_rate : 0.90,mpesa_time : 2021-09-30 14:02:57,duration : 7,merchant_id : 2c44c80b-19ff-4c25-9706-65bae...,created_at : 2021-09-30 14:02:51,2021-09-30 17:16:19+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 12450,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 2,npa_accounts : 2,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 0,created_at : 2021-09-30 14:02:51,2021-09-30 17:16:19+00,00:33:41.800000
4,112338.0,9f68c51b-ceae-40d4-b1c2-c454bfb80e29,101044,app_amount : 3656.00,app_interest_rate : 0.90,mpesa_time : 2021-09-30 13:59:49,duration : 7,merchant_id : 9f68c51b-ceae-40d4-b1c2-c454b...,created_at : 2021-09-30 13:59:43,2021-09-30 17:06:16+00,...,last_mobi_loan_listing_date_other_sectors : ...,max_mobi_loan_principal_amount : 1500,npa_closed_mobi_loan_accounts : 0,pa_open_accounts : 0,npa_accounts : 1,pa_open_mobi_loan_accounts_with_dh : 0,pa_closed_accounts_with_dh : 0,created_at : 2021-09-30 13:59:43,2021-09-30 17:06:16+00,00:54:48.300000

In [91]:
for i in new_test.iloc[:,3:-2]:
     new_test[i] = new_test[i].str.split(": ").str[1]

In [92]:
for i in new_train.iloc[:,3:-2]:
    new_train[i] = new_train[i].str.split(": ").str[1]

In [93]:
new_train.head()

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at1,created_at2,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at3,created_at4,updated_at
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100800,9160.00,0.90,2021-09-27 10:22:01,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-09-27 10:21:55,NaN,...,null,6000,0,0,1,0,1,2021-09-27 10:21:55,2021-09-27 13:36:45+00,54:44.3
1,98125.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100339,8517.00,0.90,2021-09-18 15:23:04,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-09-18 15:22:57,NaN,...,null,6000,0,0,1,0,1,2021-09-18 15:22:57,2021-09-18 18:36:39+00,44:39.4
2,84249.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99723,7635.00,0.90,2021-09-07 11:45:41,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-09-07 11:45:34,NaN,...,null,6000,0,0,1,0,1,2021-09-07 11:45:34,2021-09-07 14:57:22+00,56:36.6
3,74877.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99359,7635.00,0.90,2021-08-31 09:01:56,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-08-31 09:01:50,NaN,...,null,6000,0,0,1,0,1,2021-08-31 09:01:50,2021-08-31 12:08:12+00,48:15.4
4,61454.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,98522,7635.00,0.90,2021-08-16 08:52:59,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-08-14 09:24:20,NaN,...,null,6000,0,0,1,0,1,2021-08-14 09:24:20,2021-08-23 12:41:30+00,50:01.1

In [94]:
new_test.head()

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at1,created_at2,...,last_mobi_loan_listing_date_other_sectors,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at3,created_at4,updated_at
0,111915.0,40998a72-655b-48ab-be6d-5ba70c03fc6f,101051,1891.00,0.90,2021-09-30 16:44:33,7,40998a72-655b-48ab-be6d-5ba70c03fc6f,2021-09-30 16:44:26,NaN,...,null,30000,0,1,3,0,1,2021-09-30 16:44:26,2021-09-30 19:56:20+00,00:33:42.100000
1,111603.0,3a4f60b6-be62-47a9-9c81-67f3caada902,101048,1520.00,0.90,2021-09-30 15:56:51,7,3a4f60b6-be62-47a9-9c81-67f3caada902,2021-09-30 15:56:45,NaN,...,null,4000,0,1,0,0,1,2021-09-30 15:56:45,2021-09-30 19:06:30+00,00:16:14.300000
2,111703.0,c198ed2e-5383-4a11-8b4d-e0f93466fbc9,101046,1568.00,0.90,2021-09-30 14:26:10,7,c198ed2e-5383-4a11-8b4d-e0f93466fbc9,2021-09-30 14:26:02,NaN,...,null,0,0,1,0,0,0,2021-09-30 14:26:02,2021-09-30 17:36:15+00,00:36:29.600000
3,112113.0,2c44c80b-19ff-4c25-9706-65bae6cbfda6,101045,7855.00,0.90,2021-09-30 14:02:57,7,2c44c80b-19ff-4c25-9706-65bae6cbfda6,2021-09-30 14:02:51,NaN,...,null,12450,0,2,2,0,0,2021-09-30 14:02:51,2021-09-30 17:16:19+00,00:33:41.800000
4,112338.0,9f68c51b-ceae-40d4-b1c2-c454bfb80e29,101044,3656.00,0.90,2021-09-30 13:59:49,7,9f68c51b-ceae-40d4-b1c2-c454bfb80e29,2021-09-30 13:59:43,NaN,...,null,1500,0,0,1,0,0,2021-09-30 13:59:43,2021-09-30 17:06:16+00,00:54:48.300000

In [95]:
# new_train.created_at3 = pd.to_datetime(new_train.created_at3)
# new_train.created_at4 = pd.to_datetime(new_train.created_at4)

# new_test.created_at3 = pd.to_datetime(new_test.created_at3)
# new_test.created_at4 = pd.to_datetime(new_test.created_at4)

In [96]:
from datetime import datetime, timezone
new_train['created_at3'] = pd.to_datetime(new_train.created_at3, format='%Y-%m-%d', utc=True)
new_train['created_at4'] = pd.to_datetime(new_train.created_at4, format='%Y-%m-%d', utc=True) #tz='UTC'
new_test['created_at3'] = pd.to_datetime(new_test.created_at3, format='%Y-%m-%d', utc=True)
new_test['created_at4'] = pd.to_datetime(new_test.created_at4, format='%Y-%m-%d', utc=True)

In [97]:
new_train['days'] = new_train['created_at4'] - new_train['created_at3']
new_test['days'] = new_test['created_at4'] - new_test['created_at3']

In [98]:
new_train['days'] =new_train['days'].dt.days
new_test['days'] =new_test['days'].dt.days

In [99]:
new_train.head()

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at1,created_at2,...,max_mobi_loan_principal_amount,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at3,created_at4,updated_at,days
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100800,9160.00,0.90,2021-09-27 10:22:01,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-09-27 10:21:55,NaN,...,6000,0,0,1,0,1,2021-09-27 10:21:55+00:00,2021-09-27 13:36:45+00:00,54:44.3,0
1,98125.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100339,8517.00,0.90,2021-09-18 15:23:04,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-09-18 15:22:57,NaN,...,6000,0,0,1,0,1,2021-09-18 15:22:57+00:00,2021-09-18 18:36:39+00:00,44:39.4,0
2,84249.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99723,7635.00,0.90,2021-09-07 11:45:41,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-09-07 11:45:34,NaN,...,6000,0,0,1,0,1,2021-09-07 11:45:34+00:00,2021-09-07 14:57:22+00:00,56:36.6,0
3,74877.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99359,7635.00,0.90,2021-08-31 09:01:56,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-08-31 09:01:50,NaN,...,6000,0,0,1,0,1,2021-08-31 09:01:50+00:00,2021-08-31 12:08:12+00:00,48:15.4,0
4,61454.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,98522,7635.00,0.90,2021-08-16 08:52:59,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-08-14 09:24:20,NaN,...,6000,0,0,1,0,1,2021-08-14 09:24:20+00:00,2021-08-23 12:41:30+00:00,50:01.1,9

In [100]:
new_train['days']

0         0
1         0
2         0
3         0
4         9
       ...
4221    189
4222    200
4223    200
4224    202
4225    215
Name: days, Length: 4226, dtype: int64

In [101]:
loans = []
for i in new_train['days']:
    if i > 45:
        loans.append('1')
    else:
        loans.append('0')

In [102]:
new_train['loan_days'] = loans

In [103]:
new_train

,id,merchant_id,loan_id,app_amount,app_interest_rate,mpesa_time,duration,merchant_id1,created_at1,created_at2,...,npa_closed_mobi_loan_accounts,pa_open_accounts,npa_accounts,pa_open_mobi_loan_accounts_with_dh,pa_closed_accounts_with_dh,created_at3,created_at4,updated_at,days,loan_days
0,107661.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100800,9160.00,0.90,2021-09-27 10:22:01,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-09-27 10:21:55,NaN,...,0,0,1,0,1,2021-09-27 10:21:55+00:00,2021-09-27 13:36:45+00:00,54:44.3,0,0
1,98125.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,100339,8517.00,0.90,2021-09-18 15:23:04,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-09-18 15:22:57,NaN,...,0,0,1,0,1,2021-09-18 15:22:57+00:00,2021-09-18 18:36:39+00:00,44:39.4,0,0
2,84249.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99723,7635.00,0.90,2021-09-07 11:45:41,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-09-07 11:45:34,NaN,...,0,0,1,0,1,2021-09-07 11:45:34+00:00,2021-09-07 14:57:22+00:00,56:36.6,0,0
3,74877.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,99359,7635.00,0.90,2021-08-31 09:01:56,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-08-31 09:01:50,NaN,...,0,0,1,0,1,2021-08-31 09:01:50+00:00,2021-08-31 12:08:12+00:00,48:15.4,0,0
4,61454.0,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,98522,7635.00,0.90,2021-08-16 08:52:59,7,56cebec0-3bf6-43a8-bf32-66bb6c73bc59,2021-08-14 09:24:20,NaN,...,0,0,1,0,1,2021-08-14 09:24:20+00:00,2021-08-23 12:41:30+00:00,50:01.1,9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4221,189.0,ad7f4e53-06c6-4c19-865a-5de4d9088d4a,92559,6870.00,0.90,2020-10-12 12:22:45,15,ad7f4e53-06c6-4c19-865a-5de4d9088d4a,2020-10-12 12:22:40,NaN,...,NaN,NaN,NaN,NaN,NaN,2020-10-12 12:22:40+00:00,2021-04-20 12:03:02+00:00,30:10.4,189,1
4222,231.0,959ab23f-9d52-4d90-b15b-101048abd61f,92449,1384.00,9.00,2020-10-02 05:59:21,15,959ab23f-9d52-4d90-b15b-101048abd61f,2020-10-02 05:59:16,NaN,...,0,1,0,0,0,2020-10-02 05:59:16+00:00,2021-04-20 12:00:02+00:00,30:09.1,200,1
4223,161.0,a775435d-d999-424e-9181-bfe55902b6e7,92452,1500.00,9.00,2020-10-02 07:53:38,15,a775435d-d999-424e-9181-bfe55902b6e7,2020-10-02 07:53:33,NaN,...,0,1,0,0,0,2020-10-02 07:53:33+00:00,2021-04-20 12:00:02+00:00,30:09.5,200,1
4224,339.0,bb1cfb08-bd30-4870-b0ba-a45222961769,92415,9000.00,10.80,2020-09-30 10:39:30,15,bb1cfb08-bd30-4870-b0ba-a45222961769,2020-09-30 10:39:25,NaN,...,0,0,0,0,0,2020-09-30 10:39:25+00:00,2021-04-20 11:57:05+00:00,45:12.7,202,1
4225,294.0,5d1df13b-ae7d-4ade-b2dc-92793f4add82,92212,813.00,22.50,2020-09-17 08:23:48,15,5d1df13b-ae7d-4ade-b2dc-92793f4add82,2020-09-17 08:23:42,NaN,...,0,0,1,0,0,2020-09-17 08:23:42+00:00,2021-04-20 11:54:01+00:00,30:06.9,215,1

In [104]:
new_train.to_csv('final_train.csv')
new_test.to_csv('final_test.csv')